import {
  AcademicCapIcon,
  AdjustmentsHorizontalIcon,
  AdjustmentsVerticalIcon,
  ArchiveBoxArrowDownIcon,
  ArchiveBoxIcon,
  ArchiveBoxXMarkIcon,
  ArrowDownCircleIcon,
  ArrowDownIcon,
  ArrowDownLeftIcon,
  ArrowDownOnSquareIcon,
  ArrowDownOnSquareStackIcon,
  ArrowDownRightIcon,
  ArrowDownTrayIcon,
  ArrowLeftCircleIcon,
  ArrowLeftEndOnRectangleIcon,
  ArrowLeftIcon,
  ArrowLeftOnRectangleIcon,
  ArrowLeftStartOnRectangleIcon,
  ArrowLongDownIcon,
  ArrowLongLeftIcon,
  ArrowLongRightIcon,
  ArrowLongUpIcon,
  ArrowPathIcon,
  ArrowPathRoundedSquareIcon,
  ArrowRightCircleIcon,
  ArrowRightEndOnRectangleIcon,
  ArrowRightIcon,
  ArrowRightOnRectangleIcon,
  ArrowRightStartOnRectangleIcon,
  ArrowSmallDownIcon,
  ArrowSmallLeftIcon,
  ArrowSmallRightIcon,
  ArrowSmallUpIcon,
  ArrowTopRightOnSquareIcon,
  ArrowTrendingDownIcon,
  ArrowTrendingUpIcon,
  ArrowTurnDownLeftIcon,
  ArrowTurnDownRightIcon,
  ArrowTurnLeftDownIcon,
  ArrowTurnLeftUpIcon,
  ArrowTurnRightDownIcon,
  ArrowTurnRightUpIcon,
  ArrowTurnUpLeftIcon,
  ArrowTurnUpRightIcon,
  ArrowUpCircleIcon,
  ArrowUpIcon,
  ArrowUpLeftIcon,
  ArrowUpOnSquareIcon,
  ArrowUpOnSquareStackIcon,
  ArrowUpRightIcon,
  ArrowUpTrayIcon,
  ArrowUturnDownIcon,
  ArrowUturnLeftIcon,
  ArrowUturnRightIcon,
  ArrowUturnUpIcon,
  ArrowsPointingInIcon,
  ArrowsPointingOutIcon,
  ArrowsRightLeftIcon,
  ArrowsUpDownIcon,
  AtSymbolIcon,
  BackspaceIcon,
  BackwardIcon,
  BanknotesIcon,
  Bars2Icon,
  Bars3BottomLeftIcon,
  Bars3BottomRightIcon,
  Bars3CenterLeftIcon,
  Bars3Icon,
  Bars4Icon,
  BarsArrowDownIcon,
  BarsArrowUpIcon,
  Battery0Icon,
  Battery100Icon,
  Battery50Icon,
  BeakerIcon,
  BellAlertIcon,
  BellIcon,
  BellSlashIcon,
  BellSnoozeIcon,
  BoldIcon,
  BoltIcon,
  BoltSlashIcon,
  BookOpenIcon,
  BookmarkIcon,
  BookmarkSlashIcon,
  BookmarkSquareIcon,
  BriefcaseIcon,
  BugAntIcon,
  BuildingLibraryIcon,
  BuildingOffice2Icon,
  BuildingOfficeIcon,
  BuildingStorefrontIcon,
  CakeIcon,
  ChartBarIcon,
  DocumentTextIcon,
  GlobeAltIcon,
  LightBulbIcon,
  MegaphoneIcon,
  ScaleIcon,
  ShieldCheckIcon,
  UsersIcon,
} from '@heroicons/react/24/outline'

const iconMap = {
  globe: GlobeAltIcon,
  academicCap: AcademicCapIcon,
  adjustmentsHorizontal: AdjustmentsHorizontalIcon,
  adjustmentsVertical: AdjustmentsVerticalIcon,
  archiveBoxArrowDown: ArchiveBoxArrowDownIcon,
  archiveBox: ArchiveBoxIcon,
  archiveBoxXMark: ArchiveBoxXMarkIcon,
  arrowDownCircle: ArrowDownCircleIcon,
  arrowDown: ArrowDownIcon,
  arrowDownLeft: ArrowDownLeftIcon,
  arrowDownOnSquare: ArrowDownOnSquareIcon,
  arrowDownOnSquareStack: ArrowDownOnSquareStackIcon,
  arrowDownRight: ArrowDownRightIcon,
  arrowDownTray: ArrowDownTrayIcon,
  arrowLeftCircle: ArrowLeftCircleIcon,
  arrowLeftEndOnRectangle: ArrowLeftEndOnRectangleIcon,
  arrowLeft: ArrowLeftIcon,
  arrowLeftOnRectangle: ArrowLeftOnRectangleIcon,
  arrowLeftStartOnRectangle: ArrowLeftStartOnRectangleIcon,
  arrowLongDown: ArrowLongDownIcon,
  arrowLongLeft: ArrowLongLeftIcon,
  arrowLongRight: ArrowLongRightIcon,
  arrowLongUp: ArrowLongUpIcon,
  arrowPath: ArrowPathIcon,
  arrowPathRoundedSquare: ArrowPathRoundedSquareIcon,
  arrowRightCircle: ArrowRightCircleIcon,
  arrowRightEndOnRectangle: ArrowRightEndOnRectangleIcon,
  arrowRight: ArrowRightIcon,
  arrowRightOnRectangle: ArrowRightOnRectangleIcon,
  arrowRightStartOnRectangle: ArrowRightStartOnRectangleIcon,
  arrowSmallDown: ArrowSmallDownIcon,
  arrowSmallLeft: ArrowSmallLeftIcon,
  arrowSmallRight: ArrowSmallRightIcon,
  arrowSmallUp: ArrowSmallUpIcon,
  arrowTopRightOnSquare: ArrowTopRightOnSquareIcon,
  arrowTrendingDown: ArrowTrendingDownIcon,
  arrowTrendingUp: ArrowTrendingUpIcon,
  arrowTurnDownLeft: ArrowTurnDownLeftIcon,
  arrowTurnDownRight: ArrowTurnDownRightIcon,
  arrowTurnLeftDown: ArrowTurnLeftDownIcon,
  arrowTurnLeftUp: ArrowTurnLeftUpIcon,
  arrowTurnRightDown: ArrowTurnRightDownIcon,
  arrowTurnRightUp: ArrowTurnRightUpIcon,
  arrowTurnUpLeft: ArrowTurnUpLeftIcon,
  arrowTurnUpRight: ArrowTurnUpRightIcon,
  arrowUpCircle: ArrowUpCircleIcon,
  arrowUp: ArrowUpIcon,
  arrowUpLeft: ArrowUpLeftIcon,
  arrowUpOnSquare: ArrowUpOnSquareIcon,
  arrowUpOnSquareStack: ArrowUpOnSquareStackIcon,
  arrowUpRight: ArrowUpRightIcon,
  arrowUpTray: ArrowUpTrayIcon,
  arrowUturnDown: ArrowUturnDownIcon,
  arrowUturnLeft: ArrowUturnLeftIcon,
  arrowUturnRight: ArrowUturnRightIcon,
  arrowUturnUp: ArrowUturnUpIcon,
  arrowsPointingIn: ArrowsPointingInIcon,
  arrowsPointingOut: ArrowsPointingOutIcon,
  arrowsRightLeft: ArrowsRightLeftIcon,
  arrowsUpDown: ArrowsUpDownIcon,
  atSymbol: AtSymbolIcon,
  backspace: BackspaceIcon,
  backward: BackwardIcon,
  banknotes: BanknotesIcon,
  bars2: Bars2Icon,
  bars3BottomLeft: Bars3BottomLeftIcon,
  bars3BottomRight: Bars3BottomRightIcon,
  bars3CenterLeft: Bars3CenterLeftIcon,
  bars3: Bars3Icon,
  bars4: Bars4Icon,
  barsArrowDown: BarsArrowDownIcon,
  barsArrowUp: BarsArrowUpIcon,
  battery0: Battery0Icon,
  battery100: Battery100Icon,
  battery50: Battery50Icon,
  beaker: BeakerIcon,
  bellAlert: BellAlertIcon,
  bell: BellIcon,
  bellSlash: BellSlashIcon,
  bellSnooze: BellSnoozeIcon,
  bold: BoldIcon,
  bolt: BoltIcon,
  boltSlash: BoltSlashIcon,
  bookOpen: BookOpenIcon,
  bookmark: BookmarkIcon,
  bookmarkSlash: BookmarkSlashIcon,
  bookmarkSquare: BookmarkSquareIcon,
  briefcase: BriefcaseIcon,
  bugAnt: BugAntIcon,
  buildingLibrary: BuildingLibraryIcon,
  buildingOffice2: BuildingOffice2Icon,
  buildingOffice: BuildingOfficeIcon,
  buildingStorefront: BuildingStorefrontIcon,
  cake: CakeIcon,
  chartBar: ChartBarIcon,
  documentText: DocumentTextIcon,
  globeAlt: GlobeAltIcon,
  lightBulb: LightBulbIcon,
  megaphone: MegaphoneIcon,
  scale: ScaleIcon,
  shieldCheck: ShieldCheckIcon,
  users: UsersIcon,
} as const

type IconKey = keyof typeof iconMap

type IconBadgeProps = {
  name?: string
}

export function IconBadge({ name }: IconBadgeProps) {
  if (!name) return null
  const Icon = iconMap[name as IconKey]
  if (!Icon) return null
  return (
    <div className="mb-3">
      <span className="inline-flex h-10 w-10 items-center justify-center rounded-full bg-slate-100 text-slate-700">
        <Icon className="h-5 w-5" />
      </span>
    </div>
  )
}
