/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    datasets: Dataset;
    pages: Page;
    policyBriefs: PolicyBrief;
    events: Event;
    partners: Partner;
    'form-submissions': FormSubmission;
    leadership: Leadership;
    inTheNews: InTheNew;
    eventReports: EventReport;
    eventRegistrations: EventRegistration;
    pdfGatedDownloads: PdfGatedDownload;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    datasets: DatasetsSelect<false> | DatasetsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    policyBriefs: PolicyBriefsSelect<false> | PolicyBriefsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    leadership: LeadershipSelect<false> | LeadershipSelect<true>;
    inTheNews: InTheNewsSelect<false> | InTheNewsSelect<true>;
    eventReports: EventReportsSelect<false> | EventReportsSelect<true>;
    eventRegistrations: EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    pdfGatedDownloads: PdfGatedDownloadsSelect<false> | PdfGatedDownloadsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasets".
 */
export interface Dataset {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  columns?:
    | {
        key?: string | null;
        label?: string | null;
        type?: ('string' | 'number' | 'date') | null;
        id?: string | null;
      }[]
    | null;
  rows?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rowCount?: number | null;
  isTruncated?: boolean | null;
  parseError?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  /**
   * Override content placeholder behavior for this page.
   */
  placeholderOverride?: ('default' | 'forceOn' | 'forceOff') | null;
  layout?:
    | (
        | {
            headline?: string | null;
            subheadline?: string | null;
            eyebrow?: string | null;
            backgroundImage?: (number | null) | Media;
            /**
             * Optional: use a direct image URL instead of uploading to Media.
             */
            backgroundImageUrl?: string | null;
            latestLink?: {
              label?: string | null;
              url?: string | null;
            };
            impactTitle?: string | null;
            impactItems?:
              | {
                  value?: string | null;
                  label?: string | null;
                  icon?:
                    | (
                        | 'academicCap'
                        | 'adjustmentsHorizontal'
                        | 'adjustmentsVertical'
                        | 'archiveBoxArrowDown'
                        | 'archiveBox'
                        | 'archiveBoxXMark'
                        | 'arrowDownCircle'
                        | 'arrowDown'
                        | 'arrowDownLeft'
                        | 'arrowDownOnSquare'
                        | 'arrowDownOnSquareStack'
                        | 'arrowDownRight'
                        | 'arrowDownTray'
                        | 'arrowLeftCircle'
                        | 'arrowLeftEndOnRectangle'
                        | 'arrowLeft'
                        | 'arrowLeftOnRectangle'
                        | 'arrowLeftStartOnRectangle'
                        | 'arrowLongDown'
                        | 'arrowLongLeft'
                        | 'arrowLongRight'
                        | 'arrowLongUp'
                        | 'arrowPath'
                        | 'arrowPathRoundedSquare'
                        | 'arrowRightCircle'
                        | 'arrowRightEndOnRectangle'
                        | 'arrowRight'
                        | 'arrowRightOnRectangle'
                        | 'arrowRightStartOnRectangle'
                        | 'arrowSmallDown'
                        | 'arrowSmallLeft'
                        | 'arrowSmallRight'
                        | 'arrowSmallUp'
                        | 'arrowTopRightOnSquare'
                        | 'arrowTrendingDown'
                        | 'arrowTrendingUp'
                        | 'arrowTurnDownLeft'
                        | 'arrowTurnDownRight'
                        | 'arrowTurnLeftDown'
                        | 'arrowTurnLeftUp'
                        | 'arrowTurnRightDown'
                        | 'arrowTurnRightUp'
                        | 'arrowTurnUpLeft'
                        | 'arrowTurnUpRight'
                        | 'arrowUpCircle'
                        | 'arrowUp'
                        | 'arrowUpLeft'
                        | 'arrowUpOnSquare'
                        | 'arrowUpOnSquareStack'
                        | 'arrowUpRight'
                        | 'arrowUpTray'
                        | 'arrowUturnDown'
                        | 'arrowUturnLeft'
                        | 'arrowUturnRight'
                        | 'arrowUturnUp'
                        | 'arrowsPointingIn'
                        | 'arrowsPointingOut'
                        | 'arrowsRightLeft'
                        | 'arrowsUpDown'
                        | 'atSymbol'
                        | 'backspace'
                        | 'backward'
                        | 'banknotes'
                        | 'bars2'
                        | 'bars3BottomLeft'
                        | 'bars3BottomRight'
                        | 'bars3CenterLeft'
                        | 'bars3'
                        | 'bars4'
                        | 'barsArrowDown'
                        | 'barsArrowUp'
                        | 'battery0'
                        | 'battery100'
                        | 'battery50'
                        | 'beaker'
                        | 'bellAlert'
                        | 'bell'
                        | 'bellSlash'
                        | 'bellSnooze'
                        | 'bold'
                        | 'bolt'
                        | 'boltSlash'
                        | 'bookOpen'
                        | 'bookmark'
                        | 'bookmarkSlash'
                        | 'bookmarkSquare'
                        | 'briefcase'
                        | 'bugAnt'
                        | 'buildingLibrary'
                        | 'buildingOffice2'
                        | 'buildingOffice'
                        | 'buildingStorefront'
                        | 'cake'
                        | 'documentText'
                        | 'globeAlt'
                        | 'lightBulb'
                        | 'megaphone'
                        | 'scale'
                        | 'shieldCheck'
                        | 'users'
                      )
                    | null;
                  id?: string | null;
                }[]
              | null;
            primaryCTA?: {
              label?: string | null;
              url?: string | null;
            };
            secondaryCTA?: {
              label?: string | null;
              url?: string | null;
            };
            alignment?: ('left' | 'center' | 'right' | 'split') | null;
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              tone?: ('dark' | 'light') | null;
              minHeight?: ('short' | 'medium' | 'large') | null;
              overlayStrength?: ('light' | 'medium' | 'strong') | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
              typography?: {
                textSize?: ('sm' | 'md' | 'lg') | null;
                lineHeight?: ('snug' | 'normal' | 'relaxed') | null;
                textAlign?: ('left' | 'center' | 'right') | null;
                leadStyle?: ('none' | 'lead') | null;
                dropCap?: ('none' | 'subtle' | 'strong') | null;
              };
              layout?: {
                columns?: ('1' | '2') | null;
                columnGap?: ('sm' | 'md' | 'lg') | null;
                maxWidth?: ('narrow' | 'standard' | 'wide' | 'full') | null;
              };
              container?: {
                surface?: ('none' | 'soft' | 'card' | 'outline' | 'gradient') | null;
                radius?: ('sm' | 'md' | 'lg') | null;
                shadow?: ('none' | 'soft' | 'medium') | null;
                innerPadding?: ('compact' | 'standard' | 'large') | null;
                borderStyle?: ('none' | 'subtle' | 'strong') | null;
              };
              callouts?: {
                highlightMode?: ('none' | 'leftBar' | 'noteBox') | null;
                highlightText?: string | null;
              };
              colors?: {
                textColor?: string | null;
                headingColor?: string | null;
                linkColor?: string | null;
                accentColor?: string | null;
                backgroundColor?: string | null;
                borderColor?: string | null;
              };
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            sectionTitle?: string | null;
            sectionIntro?: string | null;
            cards?:
              | {
                  title?: string | null;
                  description?: string | null;
                  icon?:
                    | (
                        | 'academicCap'
                        | 'adjustmentsHorizontal'
                        | 'adjustmentsVertical'
                        | 'archiveBoxArrowDown'
                        | 'archiveBox'
                        | 'archiveBoxXMark'
                        | 'arrowDownCircle'
                        | 'arrowDown'
                        | 'arrowDownLeft'
                        | 'arrowDownOnSquare'
                        | 'arrowDownOnSquareStack'
                        | 'arrowDownRight'
                        | 'arrowDownTray'
                        | 'arrowLeftCircle'
                        | 'arrowLeftEndOnRectangle'
                        | 'arrowLeft'
                        | 'arrowLeftOnRectangle'
                        | 'arrowLeftStartOnRectangle'
                        | 'arrowLongDown'
                        | 'arrowLongLeft'
                        | 'arrowLongRight'
                        | 'arrowLongUp'
                        | 'arrowPath'
                        | 'arrowPathRoundedSquare'
                        | 'arrowRightCircle'
                        | 'arrowRightEndOnRectangle'
                        | 'arrowRight'
                        | 'arrowRightOnRectangle'
                        | 'arrowRightStartOnRectangle'
                        | 'arrowSmallDown'
                        | 'arrowSmallLeft'
                        | 'arrowSmallRight'
                        | 'arrowSmallUp'
                        | 'arrowTopRightOnSquare'
                        | 'arrowTrendingDown'
                        | 'arrowTrendingUp'
                        | 'arrowTurnDownLeft'
                        | 'arrowTurnDownRight'
                        | 'arrowTurnLeftDown'
                        | 'arrowTurnLeftUp'
                        | 'arrowTurnRightDown'
                        | 'arrowTurnRightUp'
                        | 'arrowTurnUpLeft'
                        | 'arrowTurnUpRight'
                        | 'arrowUpCircle'
                        | 'arrowUp'
                        | 'arrowUpLeft'
                        | 'arrowUpOnSquare'
                        | 'arrowUpOnSquareStack'
                        | 'arrowUpRight'
                        | 'arrowUpTray'
                        | 'arrowUturnDown'
                        | 'arrowUturnLeft'
                        | 'arrowUturnRight'
                        | 'arrowUturnUp'
                        | 'arrowsPointingIn'
                        | 'arrowsPointingOut'
                        | 'arrowsRightLeft'
                        | 'arrowsUpDown'
                        | 'atSymbol'
                        | 'backspace'
                        | 'backward'
                        | 'banknotes'
                        | 'bars2'
                        | 'bars3BottomLeft'
                        | 'bars3BottomRight'
                        | 'bars3CenterLeft'
                        | 'bars3'
                        | 'bars4'
                        | 'barsArrowDown'
                        | 'barsArrowUp'
                        | 'battery0'
                        | 'battery100'
                        | 'battery50'
                        | 'beaker'
                        | 'bellAlert'
                        | 'bell'
                        | 'bellSlash'
                        | 'bellSnooze'
                        | 'bold'
                        | 'bolt'
                        | 'boltSlash'
                        | 'bookOpen'
                        | 'bookmark'
                        | 'bookmarkSlash'
                        | 'bookmarkSquare'
                        | 'briefcase'
                        | 'bugAnt'
                        | 'buildingLibrary'
                        | 'buildingOffice2'
                        | 'buildingOffice'
                        | 'buildingStorefront'
                        | 'cake'
                        | 'documentText'
                        | 'globeAlt'
                        | 'lightBulb'
                        | 'megaphone'
                        | 'scale'
                        | 'shieldCheck'
                        | 'users'
                      )
                    | null;
                  link?: {
                    label?: string | null;
                    url?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              cardStyle?: ('flat' | 'raised') | null;
              columns?: ('2' | '3' | '4') | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'cards';
          }
        | {
            title?: string | null;
            description?: string | null;
            buttonLabel?: string | null;
            buttonURL?: string | null;
            theme?: ('light' | 'dark') | null;
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              align?: ('left' | 'center') | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaSection';
          }
        | {
            media?: (number | null) | Media;
            caption?: string | null;
            alignment?: ('left' | 'center' | 'right' | 'full') | null;
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              frameStyle?: ('none' | 'outline' | 'card') | null;
              radius?: ('sm' | 'md' | 'lg') | null;
              shadow?: ('none' | 'soft' | 'medium') | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            items?:
              | {
                  question?: string | null;
                  answer?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              layout?: ('cards' | 'minimal') | null;
              columns?: ('1' | '2') | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            source?: ('inTheNews' | 'policyBriefs' | 'events') | null;
            limit?: number | null;
            layout?: ('list' | 'grid') | null;
            filterTag?: string | null;
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              cardStyle?: ('flat' | 'raised') | null;
              showImages?: boolean | null;
              dense?: boolean | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentList';
          }
        | {
            sectionTitle?: string | null;
            sectionIntro?: string | null;
            status?: ('upcoming' | 'past' | 'all') | null;
            sort?: ('dateAsc' | 'dateDesc') | null;
            limit?: number | null;
            layout?: ('list' | 'grid') | null;
            filterTag?: string | null;
            cta?: {
              label?: string | null;
              url?: string | null;
            };
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              cardStyle?: ('flat' | 'raised') | null;
              showImages?: boolean | null;
              dense?: boolean | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'eventsFeed';
          }
        | {
            sectionTitle?: string | null;
            sectionIntro?: string | null;
            sort?: ('latest' | 'oldest') | null;
            limit?: number | null;
            layout?: ('list' | 'grid') | null;
            filterTag?: string | null;
            showExcerpt?: boolean | null;
            showDate?: boolean | null;
            cta?: {
              label?: string | null;
              url?: string | null;
            };
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              cardStyle?: ('flat' | 'raised') | null;
              showImages?: boolean | null;
              dense?: boolean | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'inTheNewsFeed';
          }
        | {
            sectionTitle?: string | null;
            sectionIntro?: string | null;
            sort?: ('latest' | 'oldest') | null;
            featuredOnly?: boolean | null;
            limit?: number | null;
            layout?: ('list' | 'grid') | null;
            filterTag?: string | null;
            showSummary?: boolean | null;
            showDate?: boolean | null;
            showTags?: boolean | null;
            cta?: {
              label?: string | null;
              url?: string | null;
            };
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              cardStyle?: ('flat' | 'raised') | null;
              showImages?: boolean | null;
              dense?: boolean | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'policyBriefFeed';
          }
        | {
            headline?: string | null;
            intro?: string | null;
            columns?: ('2' | '3' | '4') | null;
            features?:
              | {
                  title?: string | null;
                  description?: string | null;
                  icon?:
                    | (
                        | 'academicCap'
                        | 'adjustmentsHorizontal'
                        | 'adjustmentsVertical'
                        | 'archiveBoxArrowDown'
                        | 'archiveBox'
                        | 'archiveBoxXMark'
                        | 'arrowDownCircle'
                        | 'arrowDown'
                        | 'arrowDownLeft'
                        | 'arrowDownOnSquare'
                        | 'arrowDownOnSquareStack'
                        | 'arrowDownRight'
                        | 'arrowDownTray'
                        | 'arrowLeftCircle'
                        | 'arrowLeftEndOnRectangle'
                        | 'arrowLeft'
                        | 'arrowLeftOnRectangle'
                        | 'arrowLeftStartOnRectangle'
                        | 'arrowLongDown'
                        | 'arrowLongLeft'
                        | 'arrowLongRight'
                        | 'arrowLongUp'
                        | 'arrowPath'
                        | 'arrowPathRoundedSquare'
                        | 'arrowRightCircle'
                        | 'arrowRightEndOnRectangle'
                        | 'arrowRight'
                        | 'arrowRightOnRectangle'
                        | 'arrowRightStartOnRectangle'
                        | 'arrowSmallDown'
                        | 'arrowSmallLeft'
                        | 'arrowSmallRight'
                        | 'arrowSmallUp'
                        | 'arrowTopRightOnSquare'
                        | 'arrowTrendingDown'
                        | 'arrowTrendingUp'
                        | 'arrowTurnDownLeft'
                        | 'arrowTurnDownRight'
                        | 'arrowTurnLeftDown'
                        | 'arrowTurnLeftUp'
                        | 'arrowTurnRightDown'
                        | 'arrowTurnRightUp'
                        | 'arrowTurnUpLeft'
                        | 'arrowTurnUpRight'
                        | 'arrowUpCircle'
                        | 'arrowUp'
                        | 'arrowUpLeft'
                        | 'arrowUpOnSquare'
                        | 'arrowUpOnSquareStack'
                        | 'arrowUpRight'
                        | 'arrowUpTray'
                        | 'arrowUturnDown'
                        | 'arrowUturnLeft'
                        | 'arrowUturnRight'
                        | 'arrowUturnUp'
                        | 'arrowsPointingIn'
                        | 'arrowsPointingOut'
                        | 'arrowsRightLeft'
                        | 'arrowsUpDown'
                        | 'atSymbol'
                        | 'backspace'
                        | 'backward'
                        | 'banknotes'
                        | 'bars2'
                        | 'bars3BottomLeft'
                        | 'bars3BottomRight'
                        | 'bars3CenterLeft'
                        | 'bars3'
                        | 'bars4'
                        | 'barsArrowDown'
                        | 'barsArrowUp'
                        | 'battery0'
                        | 'battery100'
                        | 'battery50'
                        | 'beaker'
                        | 'bellAlert'
                        | 'bell'
                        | 'bellSlash'
                        | 'bellSnooze'
                        | 'bold'
                        | 'bolt'
                        | 'boltSlash'
                        | 'bookOpen'
                        | 'bookmark'
                        | 'bookmarkSlash'
                        | 'bookmarkSquare'
                        | 'briefcase'
                        | 'bugAnt'
                        | 'buildingLibrary'
                        | 'buildingOffice2'
                        | 'buildingOffice'
                        | 'buildingStorefront'
                        | 'cake'
                        | 'documentText'
                        | 'globeAlt'
                        | 'lightBulb'
                        | 'megaphone'
                        | 'scale'
                        | 'shieldCheck'
                        | 'users'
                      )
                    | null;
                  link?: {
                    label?: string | null;
                    url?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              cardStyle?: ('flat' | 'raised') | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            media?: (number | null) | Media;
            mediaPosition?: ('left' | 'right') | null;
            background?: ('none' | 'light' | 'dark') | null;
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              imageSize?: ('small' | 'medium' | 'large') | null;
              reverseOnMobile?: boolean | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'splitSection';
          }
        | {
            headline?: string | null;
            intro?: string | null;
            layout?: ('grid' | 'row') | null;
            stats?:
              | {
                  value?: string | null;
                  label?: string | null;
                  detail?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              columns?: ('2' | '3' | '4') | null;
              numberSize?: ('sm' | 'md' | 'lg') | null;
              cardStyle?: ('flat' | 'raised') | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            headline?: string | null;
            logos?:
              | {
                  logo?: (number | null) | Media;
                  name?: string | null;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              cardStyle?: ('flat' | 'raised') | null;
              columns?: ('2' | '3' | '4' | '6') | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoCloud';
          }
        | {
            headline?: string | null;
            items?:
              | {
                  quote?: string | null;
                  name?: string | null;
                  role?: string | null;
                  organization?: string | null;
                  avatar?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              layout?: ('grid' | 'carousel') | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            headline?: string | null;
            items?:
              | {
                  title?: string | null;
                  date?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              style?: ('cards' | 'minimal') | null;
              compact?: boolean | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            headline?: string | null;
            description?: string | null;
            inputPlaceholder?: string | null;
            buttonLabel?: string | null;
            formAction?: string | null;
            finePrint?: string | null;
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              tone?: ('light' | 'dark') | null;
              layout?: ('inline' | 'stacked') | null;
              cardStyle?: ('flat' | 'raised') | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
        | {
            formType?: ('newsletter' | 'contact' | 'media' | 'policyBrief' | 'event' | 'membership') | null;
            headline?: string | null;
            description?: string | null;
            submitLabel?: string | null;
            successMessage?: string | null;
            fields?:
              | {
                  /**
                   * Machine name (e.g. email, fullName). Used as the input name.
                   */
                  name?: string | null;
                  label?: string | null;
                  type?: ('text' | 'email' | 'phone' | 'textarea' | 'select') | null;
                  placeholder?: string | null;
                  required?: boolean | null;
                  span?: ('full' | 'half') | null;
                  options?:
                    | {
                        label?: string | null;
                        value?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            destination?: {
              mode?: ('cms' | 'external') | null;
              formAction?: string | null;
            };
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
              layout?: ('stacked' | 'twoColumn') | null;
              align?: ('left' | 'center') | null;
              showLabels?: boolean | null;
              fullWidthButton?: boolean | null;
              cardStyle?: ('none' | 'soft' | 'card' | 'outline') | null;
              radius?: ('sm' | 'md' | 'lg') | null;
              shadow?: ('none' | 'soft' | 'medium') | null;
              buttonStyle?: ('solid' | 'outline') | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'form';
          }
        | {
            left?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            right?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            background?: ('none' | 'light' | 'dark') | null;
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              gap?: ('sm' | 'md' | 'lg') | null;
              verticalAlign?: ('top' | 'center') | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoColumnRichText';
          }
        | {
            headline?: string | null;
            intro?: string | null;
            tiers?:
              | {
                  name?: string | null;
                  price?: string | null;
                  description?: string | null;
                  features?:
                    | {
                        feature?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  ctaLabel?: string | null;
                  ctaUrl?: string | null;
                  highlight?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              columns?: ('2' | '3' | '4') | null;
              cardStyle?: ('flat' | 'raised') | null;
              highlightStyle?: ('solid' | 'outline') | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            headline?: string | null;
            embedUrl?: string | null;
            caption?: string | null;
            aspectRatio?: ('16:9' | '4:3' | '1:1') | null;
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              frameStyle?: ('none' | 'outline' | 'card') | null;
              radius?: ('sm' | 'md' | 'lg') | null;
              shadow?: ('none' | 'soft' | 'medium') | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoEmbed';
          }
        | {
            headline?: string | null;
            description?: string | null;
            dataset?: (number | null) | Dataset;
            viewMode?: ('chart' | 'table' | 'chartAndTable') | null;
            chartType?:
              | (
                  | 'bar'
                  | 'line'
                  | 'area'
                  | 'pie'
                  | 'donut'
                  | 'stackedBar'
                  | 'groupedBar'
                  | 'scatter'
                  | 'radar'
                  | 'heatmap'
                  | 'treemap'
                )
              | null;
            indexBy?: string | null;
            valueKeys?:
              | {
                  key?: string | null;
                  id?: string | null;
                }[]
              | null;
            valueKey?: string | null;
            xKey?: string | null;
            yKey?: string | null;
            seriesKey?: string | null;
            colorScheme?: ('nivo' | 'category10' | 'paired' | 'set3' | 'spectral') | null;
            height?: number | null;
            showLegend?: boolean | null;
            /**
             * Show a placeholder for this block and allow empty required fields.
             */
            showPlaceholder?: boolean | null;
            /**
             * Show advanced layout settings.
             */
            enableAdvanced?: boolean | null;
            advanced?: {
              anchorId?: string | null;
              background?: ('none' | 'light' | 'dark') | null;
              padding?: ('none' | 'compact' | 'standard' | 'large') | null;
              width?: ('standard' | 'wide' | 'full') | null;
              panelStyle?: ('none' | 'soft' | 'card') | null;
              hideOnMobile?: boolean | null;
              hideOnDesktop?: boolean | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'dataViz';
          }
      )[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policyBriefs".
 */
export interface PolicyBrief {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  /**
   * Full executive summary (150–250 words).
   */
  executiveSummary?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Short, actionable recommendations for readers.
   */
  keyRecommendations?:
    | {
        recommendation: string;
        id?: string | null;
      }[]
    | null;
  briefType?: ('policy' | 'research' | 'report') | null;
  pdfFile?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  authors?:
    | {
        fullName: string;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  publishedAt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  startDate?: string | null;
  endDate?: string | null;
  location?: string | null;
  eventType?: string | null;
  registrationLink?: string | null;
  coverImage?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  eventStatus?: ('upcoming' | 'past') | null;
  featured?: boolean | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  website?: string | null;
  description?: string | null;
  category?: ('strategic' | 'program' | 'funding') | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  summary?: string | null;
  formType: 'newsletter' | 'contact' | 'media' | 'policyBrief' | 'event' | 'membership';
  page?: string | null;
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  organization?: string | null;
  role?: string | null;
  outlet?: string | null;
  deadline?: string | null;
  topic?: string | null;
  message?: string | null;
  data?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Read-only snapshot of the submitted fields.
   */
  details?:
    | {
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership".
 */
export interface Leadership {
  id: number;
  name: string;
  role: 'Chairman' | 'General Manager';
  bio: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  photo?: (number | null) | Media;
  socialUrl?: string | null;
  displayOrder: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inTheNews".
 */
export interface InTheNew {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedDate: string;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  originalSourceUrl?: string | null;
  originalSourceLabel?: string | null;
  coverImage?: (number | null) | Media;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventReports".
 */
export interface EventReport {
  id: number;
  event: number | Event;
  title: string;
  slug: string;
  summary?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  coverImage?: (number | null) | Media;
  pdfFile?: (number | null) | Media;
  publishedDate?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventRegistrations".
 */
export interface EventRegistration {
  id: number;
  event: number | Event;
  name: string;
  email: string;
  organisation?: string | null;
  phone?: string | null;
  extraFields?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdfGatedDownloads".
 */
export interface PdfGatedDownload {
  id: number;
  name: string;
  email: string;
  resourceType: 'policyBrief' | 'eventReport';
  policyBrief?: (number | null) | PolicyBrief;
  eventReport?: (number | null) | EventReport;
  token: string;
  tokenExpiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'datasets';
        value: number | Dataset;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'policyBriefs';
        value: number | PolicyBrief;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null)
    | ({
        relationTo: 'leadership';
        value: number | Leadership;
      } | null)
    | ({
        relationTo: 'inTheNews';
        value: number | InTheNew;
      } | null)
    | ({
        relationTo: 'eventReports';
        value: number | EventReport;
      } | null)
    | ({
        relationTo: 'eventRegistrations';
        value: number | EventRegistration;
      } | null)
    | ({
        relationTo: 'pdfGatedDownloads';
        value: number | PdfGatedDownload;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasets_select".
 */
export interface DatasetsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  columns?:
    | T
    | {
        key?: T;
        label?: T;
        type?: T;
        id?: T;
      };
  rows?: T;
  rowCount?: T;
  isTruncated?: T;
  parseError?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  placeholderOverride?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              eyebrow?: T;
              backgroundImage?: T;
              backgroundImageUrl?: T;
              latestLink?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              impactTitle?: T;
              impactItems?:
                | T
                | {
                    value?: T;
                    label?: T;
                    icon?: T;
                    id?: T;
                  };
              primaryCTA?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              secondaryCTA?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              alignment?: T;
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    padding?: T;
                    tone?: T;
                    minHeight?: T;
                    overlayStrength?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                  };
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                    typography?:
                      | T
                      | {
                          textSize?: T;
                          lineHeight?: T;
                          textAlign?: T;
                          leadStyle?: T;
                          dropCap?: T;
                        };
                    layout?:
                      | T
                      | {
                          columns?: T;
                          columnGap?: T;
                          maxWidth?: T;
                        };
                    container?:
                      | T
                      | {
                          surface?: T;
                          radius?: T;
                          shadow?: T;
                          innerPadding?: T;
                          borderStyle?: T;
                        };
                    callouts?:
                      | T
                      | {
                          highlightMode?: T;
                          highlightText?: T;
                        };
                    colors?:
                      | T
                      | {
                          textColor?: T;
                          headingColor?: T;
                          linkColor?: T;
                          accentColor?: T;
                          backgroundColor?: T;
                          borderColor?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
        cards?:
          | T
          | {
              sectionTitle?: T;
              sectionIntro?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    cardStyle?: T;
                    columns?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaSection?:
          | T
          | {
              title?: T;
              description?: T;
              buttonLabel?: T;
              buttonURL?: T;
              theme?: T;
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    align?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              media?: T;
              caption?: T;
              alignment?: T;
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    frameStyle?: T;
                    radius?: T;
                    shadow?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    layout?: T;
                    columns?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contentList?:
          | T
          | {
              source?: T;
              limit?: T;
              layout?: T;
              filterTag?: T;
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    cardStyle?: T;
                    showImages?: T;
                    dense?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                  };
              id?: T;
              blockName?: T;
            };
        eventsFeed?:
          | T
          | {
              sectionTitle?: T;
              sectionIntro?: T;
              status?: T;
              sort?: T;
              limit?: T;
              layout?: T;
              filterTag?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    cardStyle?: T;
                    showImages?: T;
                    dense?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                  };
              id?: T;
              blockName?: T;
            };
        inTheNewsFeed?:
          | T
          | {
              sectionTitle?: T;
              sectionIntro?: T;
              sort?: T;
              limit?: T;
              layout?: T;
              filterTag?: T;
              showExcerpt?: T;
              showDate?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    cardStyle?: T;
                    showImages?: T;
                    dense?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                  };
              id?: T;
              blockName?: T;
            };
        policyBriefFeed?:
          | T
          | {
              sectionTitle?: T;
              sectionIntro?: T;
              sort?: T;
              featuredOnly?: T;
              limit?: T;
              layout?: T;
              filterTag?: T;
              showSummary?: T;
              showDate?: T;
              showTags?: T;
              cta?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    cardStyle?: T;
                    showImages?: T;
                    dense?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              headline?: T;
              intro?: T;
              columns?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    cardStyle?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                  };
              id?: T;
              blockName?: T;
            };
        splitSection?:
          | T
          | {
              content?: T;
              media?: T;
              mediaPosition?: T;
              background?: T;
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    imageSize?: T;
                    reverseOnMobile?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              headline?: T;
              intro?: T;
              layout?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    detail?: T;
                    id?: T;
                  };
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    columns?: T;
                    numberSize?: T;
                    cardStyle?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logoCloud?:
          | T
          | {
              headline?: T;
              logos?:
                | T
                | {
                    logo?: T;
                    name?: T;
                    url?: T;
                    id?: T;
                  };
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    cardStyle?: T;
                    columns?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              headline?: T;
              items?:
                | T
                | {
                    quote?: T;
                    name?: T;
                    role?: T;
                    organization?: T;
                    avatar?: T;
                    id?: T;
                  };
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    layout?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              headline?: T;
              items?:
                | T
                | {
                    title?: T;
                    date?: T;
                    description?: T;
                    id?: T;
                  };
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    style?: T;
                    compact?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              headline?: T;
              description?: T;
              inputPlaceholder?: T;
              buttonLabel?: T;
              formAction?: T;
              finePrint?: T;
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    tone?: T;
                    layout?: T;
                    cardStyle?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                  };
              id?: T;
              blockName?: T;
            };
        form?:
          | T
          | {
              formType?: T;
              headline?: T;
              description?: T;
              submitLabel?: T;
              successMessage?: T;
              fields?:
                | T
                | {
                    name?: T;
                    label?: T;
                    type?: T;
                    placeholder?: T;
                    required?: T;
                    span?: T;
                    options?:
                      | T
                      | {
                          label?: T;
                          value?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              destination?:
                | T
                | {
                    mode?: T;
                    formAction?: T;
                  };
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                    layout?: T;
                    align?: T;
                    showLabels?: T;
                    fullWidthButton?: T;
                    cardStyle?: T;
                    radius?: T;
                    shadow?: T;
                    buttonStyle?: T;
                  };
              id?: T;
              blockName?: T;
            };
        twoColumnRichText?:
          | T
          | {
              left?: T;
              right?: T;
              background?: T;
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    gap?: T;
                    verticalAlign?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              headline?: T;
              intro?: T;
              tiers?:
                | T
                | {
                    name?: T;
                    price?: T;
                    description?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          id?: T;
                        };
                    ctaLabel?: T;
                    ctaUrl?: T;
                    highlight?: T;
                    id?: T;
                  };
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    columns?: T;
                    cardStyle?: T;
                    highlightStyle?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                  };
              id?: T;
              blockName?: T;
            };
        videoEmbed?:
          | T
          | {
              headline?: T;
              embedUrl?: T;
              caption?: T;
              aspectRatio?: T;
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    frameStyle?: T;
                    radius?: T;
                    shadow?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                  };
              id?: T;
              blockName?: T;
            };
        dataViz?:
          | T
          | {
              headline?: T;
              description?: T;
              dataset?: T;
              viewMode?: T;
              chartType?: T;
              indexBy?: T;
              valueKeys?:
                | T
                | {
                    key?: T;
                    id?: T;
                  };
              valueKey?: T;
              xKey?: T;
              yKey?: T;
              seriesKey?: T;
              colorScheme?: T;
              height?: T;
              showLegend?: T;
              showPlaceholder?: T;
              enableAdvanced?: T;
              advanced?:
                | T
                | {
                    anchorId?: T;
                    background?: T;
                    padding?: T;
                    width?: T;
                    panelStyle?: T;
                    hideOnMobile?: T;
                    hideOnDesktop?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policyBriefs_select".
 */
export interface PolicyBriefsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  executiveSummary?: T;
  keyRecommendations?:
    | T
    | {
        recommendation?: T;
        id?: T;
      };
  briefType?: T;
  pdfFile?: T;
  coverImage?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  authors?:
    | T
    | {
        fullName?: T;
        id?: T;
      };
  featured?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  eventType?: T;
  registrationLink?: T;
  coverImage?: T;
  description?: T;
  eventStatus?: T;
  featured?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  description?: T;
  category?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  summary?: T;
  formType?: T;
  page?: T;
  name?: T;
  email?: T;
  phone?: T;
  organization?: T;
  role?: T;
  outlet?: T;
  deadline?: T;
  topic?: T;
  message?: T;
  data?: T;
  details?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leadership_select".
 */
export interface LeadershipSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  socialUrl?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inTheNews_select".
 */
export interface InTheNewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  publishedDate?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  originalSourceUrl?: T;
  originalSourceLabel?: T;
  coverImage?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventReports_select".
 */
export interface EventReportsSelect<T extends boolean = true> {
  event?: T;
  title?: T;
  slug?: T;
  summary?: T;
  content?: T;
  coverImage?: T;
  pdfFile?: T;
  publishedDate?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventRegistrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  event?: T;
  name?: T;
  email?: T;
  organisation?: T;
  phone?: T;
  extraFields?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdfGatedDownloads_select".
 */
export interface PdfGatedDownloadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  resourceType?: T;
  policyBrief?: T;
  eventReport?: T;
  token?: T;
  tokenExpiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  /**
   * Logo for dark backgrounds (light/white variant).
   */
  logoLight?: (number | null) | Media;
  /**
   * Logo for light backgrounds (dark variant).
   */
  logoDark?: (number | null) | Media;
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  contentPlaceholders?: {
    mode?: ('off' | 'on' | 'onlyWhenEmpty') | null;
    /**
     * Shown above placeholder sections when content is empty.
     */
    label?: string | null;
  };
  socialLinks?:
    | {
        platform?: ('x' | 'facebook' | 'linkedin' | 'instagram' | 'youtube') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        label: string;
        linkType?: ('internal' | 'external') | null;
        page?: (number | null) | Page;
        /**
         * For internal links, use a path like /events or /publications/policy-brief.
         */
        url?: string | null;
        /**
         * Optional sub-navigation items.
         */
        children?:
          | {
              label: string;
              linkType?: ('internal' | 'external') | null;
              page?: (number | null) | Page;
              /**
               * For internal links, use a path like /events or /publications/policy-brief.
               */
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              linkType?: ('internal' | 'external') | null;
              page?: (number | null) | Page;
              /**
               * For internal links, use a path like /events or /publications/policy-brief.
               */
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    title?: string | null;
    description?: string | null;
    buttonLabel?: string | null;
    buttonUrl?: string | null;
    finePrint?: string | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  legalLinks?:
    | {
        label: string;
        linkType?: ('internal' | 'external') | null;
        page?: (number | null) | Page;
        /**
         * For internal links, use a path like /events or /publications/policy-brief.
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  logoLight?: T;
  logoDark?: T;
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  contentPlaceholders?:
    | T
    | {
        mode?: T;
        label?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        linkType?: T;
        page?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              linkType?: T;
              page?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              linkType?: T;
              page?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        title?: T;
        description?: T;
        buttonLabel?: T;
        buttonUrl?: T;
        finePrint?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  legalLinks?:
    | T
    | {
        label?: T;
        linkType?: T;
        page?: T;
        url?: T;
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}