/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    datasets: Dataset;
    pages: Page;
    posts: Post;
    policyBriefs: PolicyBrief;
    events: Event;
    people: Person;
    partners: Partner;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    datasets: DatasetsSelect<false> | DatasetsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    policyBriefs: PolicyBriefsSelect<false> | PolicyBriefsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    header: Header;
    footer: Footer;
    'updates-sidebar': UpdatesSidebar;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'updates-sidebar': UpdatesSidebarSelect<false> | UpdatesSidebarSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasets".
 */
export interface Dataset {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  columns?:
    | {
        key?: string | null;
        label?: string | null;
        type?: ('string' | 'number' | 'date') | null;
        id?: string | null;
      }[]
    | null;
  rows?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  rowCount?: number | null;
  isTruncated?: boolean | null;
  parseError?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout?:
    | (
        | {
            headline: string;
            subheadline?: string | null;
            backgroundImage?: (number | null) | Media;
            primaryCTA?: {
              label?: string | null;
              url?: string | null;
            };
            secondaryCTA?: {
              label?: string | null;
              url?: string | null;
            };
            alignment?: ('left' | 'center' | 'right' | 'split') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            sectionTitle: string;
            sectionIntro?: string | null;
            cards?:
              | {
                  title: string;
                  description?: string | null;
                  icon?:
                    | (
                        | 'academicCap'
                        | 'adjustmentsHorizontal'
                        | 'adjustmentsVertical'
                        | 'archiveBoxArrowDown'
                        | 'archiveBox'
                        | 'archiveBoxXMark'
                        | 'arrowDownCircle'
                        | 'arrowDown'
                        | 'arrowDownLeft'
                        | 'arrowDownOnSquare'
                        | 'arrowDownOnSquareStack'
                        | 'arrowDownRight'
                        | 'arrowDownTray'
                        | 'arrowLeftCircle'
                        | 'arrowLeftEndOnRectangle'
                        | 'arrowLeft'
                        | 'arrowLeftOnRectangle'
                        | 'arrowLeftStartOnRectangle'
                        | 'arrowLongDown'
                        | 'arrowLongLeft'
                        | 'arrowLongRight'
                        | 'arrowLongUp'
                        | 'arrowPath'
                        | 'arrowPathRoundedSquare'
                        | 'arrowRightCircle'
                        | 'arrowRightEndOnRectangle'
                        | 'arrowRight'
                        | 'arrowRightOnRectangle'
                        | 'arrowRightStartOnRectangle'
                        | 'arrowSmallDown'
                        | 'arrowSmallLeft'
                        | 'arrowSmallRight'
                        | 'arrowSmallUp'
                        | 'arrowTopRightOnSquare'
                        | 'arrowTrendingDown'
                        | 'arrowTrendingUp'
                        | 'arrowTurnDownLeft'
                        | 'arrowTurnDownRight'
                        | 'arrowTurnLeftDown'
                        | 'arrowTurnLeftUp'
                        | 'arrowTurnRightDown'
                        | 'arrowTurnRightUp'
                        | 'arrowTurnUpLeft'
                        | 'arrowTurnUpRight'
                        | 'arrowUpCircle'
                        | 'arrowUp'
                        | 'arrowUpLeft'
                        | 'arrowUpOnSquare'
                        | 'arrowUpOnSquareStack'
                        | 'arrowUpRight'
                        | 'arrowUpTray'
                        | 'arrowUturnDown'
                        | 'arrowUturnLeft'
                        | 'arrowUturnRight'
                        | 'arrowUturnUp'
                        | 'arrowsPointingIn'
                        | 'arrowsPointingOut'
                        | 'arrowsRightLeft'
                        | 'arrowsUpDown'
                        | 'atSymbol'
                        | 'backspace'
                        | 'backward'
                        | 'banknotes'
                        | 'bars2'
                        | 'bars3BottomLeft'
                        | 'bars3BottomRight'
                        | 'bars3CenterLeft'
                        | 'bars3'
                        | 'bars4'
                        | 'barsArrowDown'
                        | 'barsArrowUp'
                        | 'battery0'
                        | 'battery100'
                        | 'battery50'
                        | 'beaker'
                        | 'bellAlert'
                        | 'bell'
                        | 'bellSlash'
                        | 'bellSnooze'
                        | 'bold'
                        | 'bolt'
                        | 'boltSlash'
                        | 'bookOpen'
                        | 'bookmark'
                        | 'bookmarkSlash'
                        | 'bookmarkSquare'
                        | 'briefcase'
                        | 'bugAnt'
                        | 'buildingLibrary'
                        | 'buildingOffice2'
                        | 'buildingOffice'
                        | 'buildingStorefront'
                        | 'cake'
                        | 'documentText'
                        | 'globeAlt'
                        | 'lightBulb'
                        | 'megaphone'
                        | 'scale'
                        | 'shieldCheck'
                        | 'users'
                      )
                    | null;
                  link?: {
                    label?: string | null;
                    url?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cards';
          }
        | {
            title: string;
            description?: string | null;
            buttonLabel?: string | null;
            buttonURL?: string | null;
            theme?: ('light' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaSection';
          }
        | {
            media: number | Media;
            caption?: string | null;
            alignment?: ('left' | 'center' | 'right' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            items?:
              | {
                  question: string;
                  answer?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            source: 'posts' | 'policyBriefs' | 'events';
            limit?: number | null;
            layout?: ('list' | 'grid') | null;
            filterTag?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentList';
          }
        | {
            headline?: string | null;
            intro?: string | null;
            columns?: ('2' | '3' | '4') | null;
            features?:
              | {
                  title: string;
                  description?: string | null;
                  icon?:
                    | (
                        | 'academicCap'
                        | 'adjustmentsHorizontal'
                        | 'adjustmentsVertical'
                        | 'archiveBoxArrowDown'
                        | 'archiveBox'
                        | 'archiveBoxXMark'
                        | 'arrowDownCircle'
                        | 'arrowDown'
                        | 'arrowDownLeft'
                        | 'arrowDownOnSquare'
                        | 'arrowDownOnSquareStack'
                        | 'arrowDownRight'
                        | 'arrowDownTray'
                        | 'arrowLeftCircle'
                        | 'arrowLeftEndOnRectangle'
                        | 'arrowLeft'
                        | 'arrowLeftOnRectangle'
                        | 'arrowLeftStartOnRectangle'
                        | 'arrowLongDown'
                        | 'arrowLongLeft'
                        | 'arrowLongRight'
                        | 'arrowLongUp'
                        | 'arrowPath'
                        | 'arrowPathRoundedSquare'
                        | 'arrowRightCircle'
                        | 'arrowRightEndOnRectangle'
                        | 'arrowRight'
                        | 'arrowRightOnRectangle'
                        | 'arrowRightStartOnRectangle'
                        | 'arrowSmallDown'
                        | 'arrowSmallLeft'
                        | 'arrowSmallRight'
                        | 'arrowSmallUp'
                        | 'arrowTopRightOnSquare'
                        | 'arrowTrendingDown'
                        | 'arrowTrendingUp'
                        | 'arrowTurnDownLeft'
                        | 'arrowTurnDownRight'
                        | 'arrowTurnLeftDown'
                        | 'arrowTurnLeftUp'
                        | 'arrowTurnRightDown'
                        | 'arrowTurnRightUp'
                        | 'arrowTurnUpLeft'
                        | 'arrowTurnUpRight'
                        | 'arrowUpCircle'
                        | 'arrowUp'
                        | 'arrowUpLeft'
                        | 'arrowUpOnSquare'
                        | 'arrowUpOnSquareStack'
                        | 'arrowUpRight'
                        | 'arrowUpTray'
                        | 'arrowUturnDown'
                        | 'arrowUturnLeft'
                        | 'arrowUturnRight'
                        | 'arrowUturnUp'
                        | 'arrowsPointingIn'
                        | 'arrowsPointingOut'
                        | 'arrowsRightLeft'
                        | 'arrowsUpDown'
                        | 'atSymbol'
                        | 'backspace'
                        | 'backward'
                        | 'banknotes'
                        | 'bars2'
                        | 'bars3BottomLeft'
                        | 'bars3BottomRight'
                        | 'bars3CenterLeft'
                        | 'bars3'
                        | 'bars4'
                        | 'barsArrowDown'
                        | 'barsArrowUp'
                        | 'battery0'
                        | 'battery100'
                        | 'battery50'
                        | 'beaker'
                        | 'bellAlert'
                        | 'bell'
                        | 'bellSlash'
                        | 'bellSnooze'
                        | 'bold'
                        | 'bolt'
                        | 'boltSlash'
                        | 'bookOpen'
                        | 'bookmark'
                        | 'bookmarkSlash'
                        | 'bookmarkSquare'
                        | 'briefcase'
                        | 'bugAnt'
                        | 'buildingLibrary'
                        | 'buildingOffice2'
                        | 'buildingOffice'
                        | 'buildingStorefront'
                        | 'cake'
                        | 'documentText'
                        | 'globeAlt'
                        | 'lightBulb'
                        | 'megaphone'
                        | 'scale'
                        | 'shieldCheck'
                        | 'users'
                      )
                    | null;
                  link?: {
                    label?: string | null;
                    url?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            media?: (number | null) | Media;
            mediaPosition?: ('left' | 'right') | null;
            background?: ('none' | 'light' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'splitSection';
          }
        | {
            headline?: string | null;
            intro?: string | null;
            layout?: ('grid' | 'row') | null;
            stats?:
              | {
                  value: string;
                  label: string;
                  detail?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            headline?: string | null;
            logos?:
              | {
                  logo?: (number | null) | Media;
                  name?: string | null;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoCloud';
          }
        | {
            headline?: string | null;
            items?:
              | {
                  quote: string;
                  name: string;
                  role?: string | null;
                  organization?: string | null;
                  avatar?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            headline?: string | null;
            items?:
              | {
                  title: string;
                  date?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            headline?: string | null;
            description?: string | null;
            inputPlaceholder?: string | null;
            buttonLabel?: string | null;
            formAction?: string | null;
            finePrint?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
        | {
            left?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            right?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            background?: ('none' | 'light' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoColumnRichText';
          }
        | {
            headline?: string | null;
            intro?: string | null;
            tiers?:
              | {
                  name: string;
                  price?: string | null;
                  description?: string | null;
                  features?:
                    | {
                        feature?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  ctaLabel?: string | null;
                  ctaUrl?: string | null;
                  highlight?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            headline?: string | null;
            embedUrl: string;
            caption?: string | null;
            aspectRatio?: ('16:9' | '4:3' | '1:1') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoEmbed';
          }
        | {
            headline?: string | null;
            description?: string | null;
            dataset: number | Dataset;
            viewMode?: ('chart' | 'table' | 'chartAndTable') | null;
            chartType?:
              | (
                  | 'bar'
                  | 'line'
                  | 'area'
                  | 'pie'
                  | 'donut'
                  | 'stackedBar'
                  | 'groupedBar'
                  | 'scatter'
                  | 'radar'
                  | 'heatmap'
                  | 'treemap'
                )
              | null;
            indexBy?: string | null;
            valueKeys?:
              | {
                  key?: string | null;
                  id?: string | null;
                }[]
              | null;
            valueKey?: string | null;
            xKey?: string | null;
            yKey?: string | null;
            seriesKey?: string | null;
            colorScheme?: ('nivo' | 'category10' | 'paired' | 'set3' | 'spectral') | null;
            height?: number | null;
            showLegend?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dataViz';
          }
      )[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  layout?:
    | (
        | {
            headline: string;
            subheadline?: string | null;
            backgroundImage?: (number | null) | Media;
            primaryCTA?: {
              label?: string | null;
              url?: string | null;
            };
            secondaryCTA?: {
              label?: string | null;
              url?: string | null;
            };
            alignment?: ('left' | 'center' | 'right' | 'split') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richText';
          }
        | {
            sectionTitle: string;
            sectionIntro?: string | null;
            cards?:
              | {
                  title: string;
                  description?: string | null;
                  icon?:
                    | (
                        | 'academicCap'
                        | 'adjustmentsHorizontal'
                        | 'adjustmentsVertical'
                        | 'archiveBoxArrowDown'
                        | 'archiveBox'
                        | 'archiveBoxXMark'
                        | 'arrowDownCircle'
                        | 'arrowDown'
                        | 'arrowDownLeft'
                        | 'arrowDownOnSquare'
                        | 'arrowDownOnSquareStack'
                        | 'arrowDownRight'
                        | 'arrowDownTray'
                        | 'arrowLeftCircle'
                        | 'arrowLeftEndOnRectangle'
                        | 'arrowLeft'
                        | 'arrowLeftOnRectangle'
                        | 'arrowLeftStartOnRectangle'
                        | 'arrowLongDown'
                        | 'arrowLongLeft'
                        | 'arrowLongRight'
                        | 'arrowLongUp'
                        | 'arrowPath'
                        | 'arrowPathRoundedSquare'
                        | 'arrowRightCircle'
                        | 'arrowRightEndOnRectangle'
                        | 'arrowRight'
                        | 'arrowRightOnRectangle'
                        | 'arrowRightStartOnRectangle'
                        | 'arrowSmallDown'
                        | 'arrowSmallLeft'
                        | 'arrowSmallRight'
                        | 'arrowSmallUp'
                        | 'arrowTopRightOnSquare'
                        | 'arrowTrendingDown'
                        | 'arrowTrendingUp'
                        | 'arrowTurnDownLeft'
                        | 'arrowTurnDownRight'
                        | 'arrowTurnLeftDown'
                        | 'arrowTurnLeftUp'
                        | 'arrowTurnRightDown'
                        | 'arrowTurnRightUp'
                        | 'arrowTurnUpLeft'
                        | 'arrowTurnUpRight'
                        | 'arrowUpCircle'
                        | 'arrowUp'
                        | 'arrowUpLeft'
                        | 'arrowUpOnSquare'
                        | 'arrowUpOnSquareStack'
                        | 'arrowUpRight'
                        | 'arrowUpTray'
                        | 'arrowUturnDown'
                        | 'arrowUturnLeft'
                        | 'arrowUturnRight'
                        | 'arrowUturnUp'
                        | 'arrowsPointingIn'
                        | 'arrowsPointingOut'
                        | 'arrowsRightLeft'
                        | 'arrowsUpDown'
                        | 'atSymbol'
                        | 'backspace'
                        | 'backward'
                        | 'banknotes'
                        | 'bars2'
                        | 'bars3BottomLeft'
                        | 'bars3BottomRight'
                        | 'bars3CenterLeft'
                        | 'bars3'
                        | 'bars4'
                        | 'barsArrowDown'
                        | 'barsArrowUp'
                        | 'battery0'
                        | 'battery100'
                        | 'battery50'
                        | 'beaker'
                        | 'bellAlert'
                        | 'bell'
                        | 'bellSlash'
                        | 'bellSnooze'
                        | 'bold'
                        | 'bolt'
                        | 'boltSlash'
                        | 'bookOpen'
                        | 'bookmark'
                        | 'bookmarkSlash'
                        | 'bookmarkSquare'
                        | 'briefcase'
                        | 'bugAnt'
                        | 'buildingLibrary'
                        | 'buildingOffice2'
                        | 'buildingOffice'
                        | 'buildingStorefront'
                        | 'cake'
                        | 'documentText'
                        | 'globeAlt'
                        | 'lightBulb'
                        | 'megaphone'
                        | 'scale'
                        | 'shieldCheck'
                        | 'users'
                      )
                    | null;
                  link?: {
                    label?: string | null;
                    url?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cards';
          }
        | {
            title: string;
            description?: string | null;
            buttonLabel?: string | null;
            buttonURL?: string | null;
            theme?: ('light' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaSection';
          }
        | {
            media: number | Media;
            caption?: string | null;
            alignment?: ('left' | 'center' | 'right' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaBlock';
          }
        | {
            items?:
              | {
                  question: string;
                  answer?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            source: 'posts' | 'policyBriefs' | 'events';
            limit?: number | null;
            layout?: ('list' | 'grid') | null;
            filterTag?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contentList';
          }
        | {
            headline?: string | null;
            intro?: string | null;
            columns?: ('2' | '3' | '4') | null;
            features?:
              | {
                  title: string;
                  description?: string | null;
                  icon?:
                    | (
                        | 'academicCap'
                        | 'adjustmentsHorizontal'
                        | 'adjustmentsVertical'
                        | 'archiveBoxArrowDown'
                        | 'archiveBox'
                        | 'archiveBoxXMark'
                        | 'arrowDownCircle'
                        | 'arrowDown'
                        | 'arrowDownLeft'
                        | 'arrowDownOnSquare'
                        | 'arrowDownOnSquareStack'
                        | 'arrowDownRight'
                        | 'arrowDownTray'
                        | 'arrowLeftCircle'
                        | 'arrowLeftEndOnRectangle'
                        | 'arrowLeft'
                        | 'arrowLeftOnRectangle'
                        | 'arrowLeftStartOnRectangle'
                        | 'arrowLongDown'
                        | 'arrowLongLeft'
                        | 'arrowLongRight'
                        | 'arrowLongUp'
                        | 'arrowPath'
                        | 'arrowPathRoundedSquare'
                        | 'arrowRightCircle'
                        | 'arrowRightEndOnRectangle'
                        | 'arrowRight'
                        | 'arrowRightOnRectangle'
                        | 'arrowRightStartOnRectangle'
                        | 'arrowSmallDown'
                        | 'arrowSmallLeft'
                        | 'arrowSmallRight'
                        | 'arrowSmallUp'
                        | 'arrowTopRightOnSquare'
                        | 'arrowTrendingDown'
                        | 'arrowTrendingUp'
                        | 'arrowTurnDownLeft'
                        | 'arrowTurnDownRight'
                        | 'arrowTurnLeftDown'
                        | 'arrowTurnLeftUp'
                        | 'arrowTurnRightDown'
                        | 'arrowTurnRightUp'
                        | 'arrowTurnUpLeft'
                        | 'arrowTurnUpRight'
                        | 'arrowUpCircle'
                        | 'arrowUp'
                        | 'arrowUpLeft'
                        | 'arrowUpOnSquare'
                        | 'arrowUpOnSquareStack'
                        | 'arrowUpRight'
                        | 'arrowUpTray'
                        | 'arrowUturnDown'
                        | 'arrowUturnLeft'
                        | 'arrowUturnRight'
                        | 'arrowUturnUp'
                        | 'arrowsPointingIn'
                        | 'arrowsPointingOut'
                        | 'arrowsRightLeft'
                        | 'arrowsUpDown'
                        | 'atSymbol'
                        | 'backspace'
                        | 'backward'
                        | 'banknotes'
                        | 'bars2'
                        | 'bars3BottomLeft'
                        | 'bars3BottomRight'
                        | 'bars3CenterLeft'
                        | 'bars3'
                        | 'bars4'
                        | 'barsArrowDown'
                        | 'barsArrowUp'
                        | 'battery0'
                        | 'battery100'
                        | 'battery50'
                        | 'beaker'
                        | 'bellAlert'
                        | 'bell'
                        | 'bellSlash'
                        | 'bellSnooze'
                        | 'bold'
                        | 'bolt'
                        | 'boltSlash'
                        | 'bookOpen'
                        | 'bookmark'
                        | 'bookmarkSlash'
                        | 'bookmarkSquare'
                        | 'briefcase'
                        | 'bugAnt'
                        | 'buildingLibrary'
                        | 'buildingOffice2'
                        | 'buildingOffice'
                        | 'buildingStorefront'
                        | 'cake'
                        | 'documentText'
                        | 'globeAlt'
                        | 'lightBulb'
                        | 'megaphone'
                        | 'scale'
                        | 'shieldCheck'
                        | 'users'
                      )
                    | null;
                  link?: {
                    label?: string | null;
                    url?: string | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'featureGrid';
          }
        | {
            content?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            media?: (number | null) | Media;
            mediaPosition?: ('left' | 'right') | null;
            background?: ('none' | 'light' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'splitSection';
          }
        | {
            headline?: string | null;
            intro?: string | null;
            layout?: ('grid' | 'row') | null;
            stats?:
              | {
                  value: string;
                  label: string;
                  detail?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            headline?: string | null;
            logos?:
              | {
                  logo?: (number | null) | Media;
                  name?: string | null;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoCloud';
          }
        | {
            headline?: string | null;
            items?:
              | {
                  quote: string;
                  name: string;
                  role?: string | null;
                  organization?: string | null;
                  avatar?: (number | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            headline?: string | null;
            items?:
              | {
                  title: string;
                  date?: string | null;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'timeline';
          }
        | {
            headline?: string | null;
            description?: string | null;
            inputPlaceholder?: string | null;
            buttonLabel?: string | null;
            formAction?: string | null;
            finePrint?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'newsletter';
          }
        | {
            left?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            right?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            background?: ('none' | 'light' | 'dark') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'twoColumnRichText';
          }
        | {
            headline?: string | null;
            intro?: string | null;
            tiers?:
              | {
                  name: string;
                  price?: string | null;
                  description?: string | null;
                  features?:
                    | {
                        feature?: string | null;
                        id?: string | null;
                      }[]
                    | null;
                  ctaLabel?: string | null;
                  ctaUrl?: string | null;
                  highlight?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pricing';
          }
        | {
            headline?: string | null;
            embedUrl: string;
            caption?: string | null;
            aspectRatio?: ('16:9' | '4:3' | '1:1') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'videoEmbed';
          }
        | {
            headline?: string | null;
            description?: string | null;
            dataset: number | Dataset;
            viewMode?: ('chart' | 'table' | 'chartAndTable') | null;
            chartType?:
              | (
                  | 'bar'
                  | 'line'
                  | 'area'
                  | 'pie'
                  | 'donut'
                  | 'stackedBar'
                  | 'groupedBar'
                  | 'scatter'
                  | 'radar'
                  | 'heatmap'
                  | 'treemap'
                )
              | null;
            indexBy?: string | null;
            valueKeys?:
              | {
                  key?: string | null;
                  id?: string | null;
                }[]
              | null;
            valueKey?: string | null;
            xKey?: string | null;
            yKey?: string | null;
            seriesKey?: string | null;
            colorScheme?: ('nivo' | 'category10' | 'paired' | 'set3' | 'spectral') | null;
            height?: number | null;
            showLegend?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'dataViz';
          }
      )[]
    | null;
  coverImage?: (number | null) | Media;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policyBriefs".
 */
export interface PolicyBrief {
  id: number;
  title: string;
  slug: string;
  summary?: string | null;
  briefType?: ('policy' | 'research' | 'report') | null;
  pdfFile?: (number | null) | Media;
  coverImage?: (number | null) | Media;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  startDate?: string | null;
  endDate?: string | null;
  location?: string | null;
  registrationLink?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  eventStatus?: ('upcoming' | 'past') | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  fullName: string;
  roleTitle?: string | null;
  photo?: (number | null) | Media;
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  email?: string | null;
  phone?: string | null;
  sortOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo?: (number | null) | Media;
  website?: string | null;
  description?: string | null;
  category?: ('strategic' | 'program' | 'funding') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'datasets';
        value: number | Dataset;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'policyBriefs';
        value: number | PolicyBrief;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "datasets_select".
 */
export interface DatasetsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  columns?:
    | T
    | {
        key?: T;
        label?: T;
        type?: T;
        id?: T;
      };
  rows?: T;
  rowCount?: T;
  isTruncated?: T;
  parseError?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              backgroundImage?: T;
              primaryCTA?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              secondaryCTA?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        cards?:
          | T
          | {
              sectionTitle?: T;
              sectionIntro?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaSection?:
          | T
          | {
              title?: T;
              description?: T;
              buttonLabel?: T;
              buttonURL?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              media?: T;
              caption?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contentList?:
          | T
          | {
              source?: T;
              limit?: T;
              layout?: T;
              filterTag?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              headline?: T;
              intro?: T;
              columns?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        splitSection?:
          | T
          | {
              content?: T;
              media?: T;
              mediaPosition?: T;
              background?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              headline?: T;
              intro?: T;
              layout?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    detail?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logoCloud?:
          | T
          | {
              headline?: T;
              logos?:
                | T
                | {
                    logo?: T;
                    name?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              headline?: T;
              items?:
                | T
                | {
                    quote?: T;
                    name?: T;
                    role?: T;
                    organization?: T;
                    avatar?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              headline?: T;
              items?:
                | T
                | {
                    title?: T;
                    date?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              headline?: T;
              description?: T;
              inputPlaceholder?: T;
              buttonLabel?: T;
              formAction?: T;
              finePrint?: T;
              id?: T;
              blockName?: T;
            };
        twoColumnRichText?:
          | T
          | {
              left?: T;
              right?: T;
              background?: T;
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              headline?: T;
              intro?: T;
              tiers?:
                | T
                | {
                    name?: T;
                    price?: T;
                    description?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          id?: T;
                        };
                    ctaLabel?: T;
                    ctaUrl?: T;
                    highlight?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        videoEmbed?:
          | T
          | {
              headline?: T;
              embedUrl?: T;
              caption?: T;
              aspectRatio?: T;
              id?: T;
              blockName?: T;
            };
        dataViz?:
          | T
          | {
              headline?: T;
              description?: T;
              dataset?: T;
              viewMode?: T;
              chartType?: T;
              indexBy?: T;
              valueKeys?:
                | T
                | {
                    key?: T;
                    id?: T;
                  };
              valueKey?: T;
              xKey?: T;
              yKey?: T;
              seriesKey?: T;
              colorScheme?: T;
              height?: T;
              showLegend?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              headline?: T;
              subheadline?: T;
              backgroundImage?: T;
              primaryCTA?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              secondaryCTA?:
                | T
                | {
                    label?: T;
                    url?: T;
                  };
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        richText?:
          | T
          | {
              content?: T;
              id?: T;
              blockName?: T;
            };
        cards?:
          | T
          | {
              sectionTitle?: T;
              sectionIntro?: T;
              cards?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        ctaSection?:
          | T
          | {
              title?: T;
              description?: T;
              buttonLabel?: T;
              buttonURL?: T;
              theme?: T;
              id?: T;
              blockName?: T;
            };
        mediaBlock?:
          | T
          | {
              media?: T;
              caption?: T;
              alignment?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        contentList?:
          | T
          | {
              source?: T;
              limit?: T;
              layout?: T;
              filterTag?: T;
              id?: T;
              blockName?: T;
            };
        featureGrid?:
          | T
          | {
              headline?: T;
              intro?: T;
              columns?: T;
              features?:
                | T
                | {
                    title?: T;
                    description?: T;
                    icon?: T;
                    link?:
                      | T
                      | {
                          label?: T;
                          url?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        splitSection?:
          | T
          | {
              content?: T;
              media?: T;
              mediaPosition?: T;
              background?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              headline?: T;
              intro?: T;
              layout?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    detail?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        logoCloud?:
          | T
          | {
              headline?: T;
              logos?:
                | T
                | {
                    logo?: T;
                    name?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              headline?: T;
              items?:
                | T
                | {
                    quote?: T;
                    name?: T;
                    role?: T;
                    organization?: T;
                    avatar?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        timeline?:
          | T
          | {
              headline?: T;
              items?:
                | T
                | {
                    title?: T;
                    date?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        newsletter?:
          | T
          | {
              headline?: T;
              description?: T;
              inputPlaceholder?: T;
              buttonLabel?: T;
              formAction?: T;
              finePrint?: T;
              id?: T;
              blockName?: T;
            };
        twoColumnRichText?:
          | T
          | {
              left?: T;
              right?: T;
              background?: T;
              id?: T;
              blockName?: T;
            };
        pricing?:
          | T
          | {
              headline?: T;
              intro?: T;
              tiers?:
                | T
                | {
                    name?: T;
                    price?: T;
                    description?: T;
                    features?:
                      | T
                      | {
                          feature?: T;
                          id?: T;
                        };
                    ctaLabel?: T;
                    ctaUrl?: T;
                    highlight?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        videoEmbed?:
          | T
          | {
              headline?: T;
              embedUrl?: T;
              caption?: T;
              aspectRatio?: T;
              id?: T;
              blockName?: T;
            };
        dataViz?:
          | T
          | {
              headline?: T;
              description?: T;
              dataset?: T;
              viewMode?: T;
              chartType?: T;
              indexBy?: T;
              valueKeys?:
                | T
                | {
                    key?: T;
                    id?: T;
                  };
              valueKey?: T;
              xKey?: T;
              yKey?: T;
              seriesKey?: T;
              colorScheme?: T;
              height?: T;
              showLegend?: T;
              id?: T;
              blockName?: T;
            };
      };
  coverImage?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "policyBriefs_select".
 */
export interface PolicyBriefsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  briefType?: T;
  pdfFile?: T;
  coverImage?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  startDate?: T;
  endDate?: T;
  location?: T;
  registrationLink?: T;
  description?: T;
  eventStatus?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  fullName?: T;
  roleTitle?: T;
  photo?: T;
  bio?: T;
  email?: T;
  phone?: T;
  sortOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  description?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  defaultSeo?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  socialLinks?:
    | {
        platform?: ('x' | 'facebook' | 'linkedin' | 'instagram' | 'youtube') | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        label: string;
        linkType?: ('internal' | 'external') | null;
        page?: (number | null) | Page;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  columns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              linkType?: ('internal' | 'external') | null;
              page?: (number | null) | Page;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  contact?: {
    email?: string | null;
    phone?: string | null;
    address?: string | null;
  };
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates-sidebar".
 */
export interface UpdatesSidebar {
  id: number;
  newsletterHeadline?: string | null;
  newsletterDescription?: string | null;
  buttonLabel?: string | null;
  formAction?: string | null;
  finePrint?: string | null;
  featuredTitle?: string | null;
  featuredLimit?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  defaultSeo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        linkType?: T;
        page?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              linkType?: T;
              page?: T;
              url?: T;
              id?: T;
            };
        id?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        address?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "updates-sidebar_select".
 */
export interface UpdatesSidebarSelect<T extends boolean = true> {
  newsletterHeadline?: T;
  newsletterDescription?: T;
  buttonLabel?: T;
  formAction?: T;
  finePrint?: T;
  featuredTitle?: T;
  featuredLimit?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}