export type IconOption = {
  label: string
  value: string
}

export const iconOptions: IconOption[] = [
  { label: 'Academic Cap', value: 'academicCap' },
  { label: 'Adjustments Horizontal', value: 'adjustmentsHorizontal' },
  { label: 'Adjustments Vertical', value: 'adjustmentsVertical' },
  { label: 'Archive Box Arrow Down', value: 'archiveBoxArrowDown' },
  { label: 'Archive Box', value: 'archiveBox' },
  { label: 'Archive Box X Mark', value: 'archiveBoxXMark' },
  { label: 'Arrow Down Circle', value: 'arrowDownCircle' },
  { label: 'Arrow Down', value: 'arrowDown' },
  { label: 'Arrow Down Left', value: 'arrowDownLeft' },
  { label: 'Arrow Down On Square', value: 'arrowDownOnSquare' },
  { label: 'Arrow Down On Square Stack', value: 'arrowDownOnSquareStack' },
  { label: 'Arrow Down Right', value: 'arrowDownRight' },
  { label: 'Arrow Down Tray', value: 'arrowDownTray' },
  { label: 'Arrow Left Circle', value: 'arrowLeftCircle' },
  { label: 'Arrow Left End On Rectangle', value: 'arrowLeftEndOnRectangle' },
  { label: 'Arrow Left', value: 'arrowLeft' },
  { label: 'Arrow Left On Rectangle', value: 'arrowLeftOnRectangle' },
  { label: 'Arrow Left Start On Rectangle', value: 'arrowLeftStartOnRectangle' },
  { label: 'Arrow Long Down', value: 'arrowLongDown' },
  { label: 'Arrow Long Left', value: 'arrowLongLeft' },
  { label: 'Arrow Long Right', value: 'arrowLongRight' },
  { label: 'Arrow Long Up', value: 'arrowLongUp' },
  { label: 'Arrow Path', value: 'arrowPath' },
  { label: 'Arrow Path Rounded Square', value: 'arrowPathRoundedSquare' },
  { label: 'Arrow Right Circle', value: 'arrowRightCircle' },
  { label: 'Arrow Right End On Rectangle', value: 'arrowRightEndOnRectangle' },
  { label: 'Arrow Right', value: 'arrowRight' },
  { label: 'Arrow Right On Rectangle', value: 'arrowRightOnRectangle' },
  { label: 'Arrow Right Start On Rectangle', value: 'arrowRightStartOnRectangle' },
  { label: 'Arrow Small Down', value: 'arrowSmallDown' },
  { label: 'Arrow Small Left', value: 'arrowSmallLeft' },
  { label: 'Arrow Small Right', value: 'arrowSmallRight' },
  { label: 'Arrow Small Up', value: 'arrowSmallUp' },
  { label: 'Arrow Top Right On Square', value: 'arrowTopRightOnSquare' },
  { label: 'Arrow Trending Down', value: 'arrowTrendingDown' },
  { label: 'Arrow Trending Up', value: 'arrowTrendingUp' },
  { label: 'Arrow Turn Down Left', value: 'arrowTurnDownLeft' },
  { label: 'Arrow Turn Down Right', value: 'arrowTurnDownRight' },
  { label: 'Arrow Turn Left Down', value: 'arrowTurnLeftDown' },
  { label: 'Arrow Turn Left Up', value: 'arrowTurnLeftUp' },
  { label: 'Arrow Turn Right Down', value: 'arrowTurnRightDown' },
  { label: 'Arrow Turn Right Up', value: 'arrowTurnRightUp' },
  { label: 'Arrow Turn Up Left', value: 'arrowTurnUpLeft' },
  { label: 'Arrow Turn Up Right', value: 'arrowTurnUpRight' },
  { label: 'Arrow Up Circle', value: 'arrowUpCircle' },
  { label: 'Arrow Up', value: 'arrowUp' },
  { label: 'Arrow Up Left', value: 'arrowUpLeft' },
  { label: 'Arrow Up On Square', value: 'arrowUpOnSquare' },
  { label: 'Arrow Up On Square Stack', value: 'arrowUpOnSquareStack' },
  { label: 'Arrow Up Right', value: 'arrowUpRight' },
  { label: 'Arrow Up Tray', value: 'arrowUpTray' },
  { label: 'Arrow Uturn Down', value: 'arrowUturnDown' },
  { label: 'Arrow Uturn Left', value: 'arrowUturnLeft' },
  { label: 'Arrow Uturn Right', value: 'arrowUturnRight' },
  { label: 'Arrow Uturn Up', value: 'arrowUturnUp' },
  { label: 'Arrows Pointing In', value: 'arrowsPointingIn' },
  { label: 'Arrows Pointing Out', value: 'arrowsPointingOut' },
  { label: 'Arrows Right Left', value: 'arrowsRightLeft' },
  { label: 'Arrows Up Down', value: 'arrowsUpDown' },
  { label: 'At Symbol', value: 'atSymbol' },
  { label: 'Backspace', value: 'backspace' },
  { label: 'Backward', value: 'backward' },
  { label: 'Banknotes', value: 'banknotes' },
  { label: 'Bars2', value: 'bars2' },
  { label: 'Bars3 Bottom Left', value: 'bars3BottomLeft' },
  { label: 'Bars3 Bottom Right', value: 'bars3BottomRight' },
  { label: 'Bars3 Center Left', value: 'bars3CenterLeft' },
  { label: 'Bars3', value: 'bars3' },
  { label: 'Bars4', value: 'bars4' },
  { label: 'Bars Arrow Down', value: 'barsArrowDown' },
  { label: 'Bars Arrow Up', value: 'barsArrowUp' },
  { label: 'Battery0', value: 'battery0' },
  { label: 'Battery100', value: 'battery100' },
  { label: 'Battery50', value: 'battery50' },
  { label: 'Beaker', value: 'beaker' },
  { label: 'Bell Alert', value: 'bellAlert' },
  { label: 'Bell', value: 'bell' },
  { label: 'Bell Slash', value: 'bellSlash' },
  { label: 'Bell Snooze', value: 'bellSnooze' },
  { label: 'Bold', value: 'bold' },
  { label: 'Bolt', value: 'bolt' },
  { label: 'Bolt Slash', value: 'boltSlash' },
  { label: 'Book Open', value: 'bookOpen' },
  { label: 'Bookmark', value: 'bookmark' },
  { label: 'Bookmark Slash', value: 'bookmarkSlash' },
  { label: 'Bookmark Square', value: 'bookmarkSquare' },
  { label: 'Briefcase', value: 'briefcase' },
  { label: 'Bug Ant', value: 'bugAnt' },
  { label: 'Building Library', value: 'buildingLibrary' },
  { label: 'Building Office2', value: 'buildingOffice2' },
  { label: 'Building Office', value: 'buildingOffice' },
  { label: 'Building Storefront', value: 'buildingStorefront' },
  { label: 'Cake', value: 'cake' },
  { label: 'Document Text', value: 'documentText' },
  { label: 'Globe Alt', value: 'globeAlt' },
  { label: 'Light Bulb', value: 'lightBulb' },
  { label: 'Megaphone', value: 'megaphone' },
  { label: 'Scale', value: 'scale' },
  { label: 'Shield Check', value: 'shieldCheck' },
  { label: 'Users', value: 'users' },
]
