FROM node:22.17.0-alpine
WORKDIR /app
RUN corepack enable
COPY pnpm-lock.yaml package.json pnpm-workspace.yaml ./
COPY patches ./patches
COPY apps/cms/package.json apps/cms/package.json
COPY apps/web/package.json apps/web/package.json
RUN pnpm install --frozen-lockfile
COPY apps/cms ./apps/cms
WORKDIR /app/apps/cms
ENV NODE_ENV=production
CMD ["pnpm","payload","migrate"]
