import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_rich_text_advanced_typography_text_size" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_advanced_typography_line_height" AS ENUM('snug', 'normal', 'relaxed');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_advanced_typography_text_align" AS ENUM('left', 'center', 'right');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_advanced_typography_lead_style" AS ENUM('none', 'lead');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_advanced_typography_drop_cap" AS ENUM('none', 'subtle', 'strong');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_advanced_layout_columns" AS ENUM('1', '2');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_advanced_layout_column_gap" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_advanced_layout_max_width" AS ENUM('narrow', 'standard', 'wide', 'full');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_advanced_container_surface" AS ENUM('none', 'soft', 'card', 'outline', 'gradient');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_advanced_container_radius" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_advanced_container_shadow" AS ENUM('none', 'soft', 'medium');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_advanced_container_inner_padding" AS ENUM('compact', 'standard', 'large');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_advanced_container_border_style" AS ENUM('none', 'subtle', 'strong');
  CREATE TYPE "public"."enum_pages_blocks_rich_text_advanced_callouts_highlight_mode" AS ENUM('none', 'leftBar', 'noteBox');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_advanced_typography_text_size" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_advanced_typography_line_height" AS ENUM('snug', 'normal', 'relaxed');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_advanced_typography_text_align" AS ENUM('left', 'center', 'right');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_advanced_typography_lead_style" AS ENUM('none', 'lead');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_advanced_typography_drop_cap" AS ENUM('none', 'subtle', 'strong');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_advanced_layout_columns" AS ENUM('1', '2');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_advanced_layout_column_gap" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_advanced_layout_max_width" AS ENUM('narrow', 'standard', 'wide', 'full');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_advanced_container_surface" AS ENUM('none', 'soft', 'card', 'outline', 'gradient');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_advanced_container_radius" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_advanced_container_shadow" AS ENUM('none', 'soft', 'medium');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_advanced_container_inner_padding" AS ENUM('compact', 'standard', 'large');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_advanced_container_border_style" AS ENUM('none', 'subtle', 'strong');
  CREATE TYPE "public"."enum__pages_v_blocks_rich_text_advanced_callouts_highlight_mode" AS ENUM('none', 'leftBar', 'noteBox');
  CREATE TYPE "public"."enum_posts_blocks_rich_text_advanced_typography_text_size" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum_posts_blocks_rich_text_advanced_typography_line_height" AS ENUM('snug', 'normal', 'relaxed');
  CREATE TYPE "public"."enum_posts_blocks_rich_text_advanced_typography_text_align" AS ENUM('left', 'center', 'right');
  CREATE TYPE "public"."enum_posts_blocks_rich_text_advanced_typography_lead_style" AS ENUM('none', 'lead');
  CREATE TYPE "public"."enum_posts_blocks_rich_text_advanced_typography_drop_cap" AS ENUM('none', 'subtle', 'strong');
  CREATE TYPE "public"."enum_posts_blocks_rich_text_advanced_layout_columns" AS ENUM('1', '2');
  CREATE TYPE "public"."enum_posts_blocks_rich_text_advanced_layout_column_gap" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum_posts_blocks_rich_text_advanced_layout_max_width" AS ENUM('narrow', 'standard', 'wide', 'full');
  CREATE TYPE "public"."enum_posts_blocks_rich_text_advanced_container_surface" AS ENUM('none', 'soft', 'card', 'outline', 'gradient');
  CREATE TYPE "public"."enum_posts_blocks_rich_text_advanced_container_radius" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum_posts_blocks_rich_text_advanced_container_shadow" AS ENUM('none', 'soft', 'medium');
  CREATE TYPE "public"."enum_posts_blocks_rich_text_advanced_container_inner_padding" AS ENUM('compact', 'standard', 'large');
  CREATE TYPE "public"."enum_posts_blocks_rich_text_advanced_container_border_style" AS ENUM('none', 'subtle', 'strong');
  CREATE TYPE "public"."enum_posts_blocks_rich_text_advanced_callouts_highlight_mode" AS ENUM('none', 'leftBar', 'noteBox');
  CREATE TYPE "public"."enum__posts_v_blocks_rich_text_advanced_typography_text_size" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum__posts_v_blocks_rich_text_advanced_typography_line_height" AS ENUM('snug', 'normal', 'relaxed');
  CREATE TYPE "public"."enum__posts_v_blocks_rich_text_advanced_typography_text_align" AS ENUM('left', 'center', 'right');
  CREATE TYPE "public"."enum__posts_v_blocks_rich_text_advanced_typography_lead_style" AS ENUM('none', 'lead');
  CREATE TYPE "public"."enum__posts_v_blocks_rich_text_advanced_typography_drop_cap" AS ENUM('none', 'subtle', 'strong');
  CREATE TYPE "public"."enum__posts_v_blocks_rich_text_advanced_layout_columns" AS ENUM('1', '2');
  CREATE TYPE "public"."enum__posts_v_blocks_rich_text_advanced_layout_column_gap" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum__posts_v_blocks_rich_text_advanced_layout_max_width" AS ENUM('narrow', 'standard', 'wide', 'full');
  CREATE TYPE "public"."enum__posts_v_blocks_rich_text_advanced_container_surface" AS ENUM('none', 'soft', 'card', 'outline', 'gradient');
  CREATE TYPE "public"."enum__posts_v_blocks_rich_text_advanced_container_radius" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum__posts_v_blocks_rich_text_advanced_container_shadow" AS ENUM('none', 'soft', 'medium');
  CREATE TYPE "public"."enum__posts_v_blocks_rich_text_advanced_container_inner_padding" AS ENUM('compact', 'standard', 'large');
  CREATE TYPE "public"."enum__posts_v_blocks_rich_text_advanced_container_border_style" AS ENUM('none', 'subtle', 'strong');
  CREATE TYPE "public"."enum__posts_v_blocks_rich_text_advanced_callouts_highlight_mode" AS ENUM('none', 'leftBar', 'noteBox');
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_typography_text_size" "enum_pages_blocks_rich_text_advanced_typography_text_size" DEFAULT 'md';
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_typography_line_height" "enum_pages_blocks_rich_text_advanced_typography_line_height" DEFAULT 'normal';
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_typography_text_align" "enum_pages_blocks_rich_text_advanced_typography_text_align" DEFAULT 'left';
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_typography_lead_style" "enum_pages_blocks_rich_text_advanced_typography_lead_style" DEFAULT 'none';
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_typography_drop_cap" "enum_pages_blocks_rich_text_advanced_typography_drop_cap" DEFAULT 'none';
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_layout_columns" "enum_pages_blocks_rich_text_advanced_layout_columns" DEFAULT '1';
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_layout_column_gap" "enum_pages_blocks_rich_text_advanced_layout_column_gap" DEFAULT 'md';
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_layout_max_width" "enum_pages_blocks_rich_text_advanced_layout_max_width" DEFAULT 'standard';
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_container_surface" "enum_pages_blocks_rich_text_advanced_container_surface" DEFAULT 'none';
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_container_radius" "enum_pages_blocks_rich_text_advanced_container_radius" DEFAULT 'md';
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_container_shadow" "enum_pages_blocks_rich_text_advanced_container_shadow" DEFAULT 'none';
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_container_inner_padding" "enum_pages_blocks_rich_text_advanced_container_inner_padding" DEFAULT 'standard';
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_container_border_style" "enum_pages_blocks_rich_text_advanced_container_border_style" DEFAULT 'none';
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_callouts_highlight_mode" "enum_pages_blocks_rich_text_advanced_callouts_highlight_mode" DEFAULT 'none';
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_callouts_highlight_text" varchar;
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_colors_text_color" varchar;
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_colors_heading_color" varchar;
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_colors_link_color" varchar;
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_colors_accent_color" varchar;
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_colors_background_color" varchar;
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "advanced_colors_border_color" varchar;
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_typography_text_size" "enum__pages_v_blocks_rich_text_advanced_typography_text_size" DEFAULT 'md';
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_typography_line_height" "enum__pages_v_blocks_rich_text_advanced_typography_line_height" DEFAULT 'normal';
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_typography_text_align" "enum__pages_v_blocks_rich_text_advanced_typography_text_align" DEFAULT 'left';
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_typography_lead_style" "enum__pages_v_blocks_rich_text_advanced_typography_lead_style" DEFAULT 'none';
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_typography_drop_cap" "enum__pages_v_blocks_rich_text_advanced_typography_drop_cap" DEFAULT 'none';
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_layout_columns" "enum__pages_v_blocks_rich_text_advanced_layout_columns" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_layout_column_gap" "enum__pages_v_blocks_rich_text_advanced_layout_column_gap" DEFAULT 'md';
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_layout_max_width" "enum__pages_v_blocks_rich_text_advanced_layout_max_width" DEFAULT 'standard';
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_container_surface" "enum__pages_v_blocks_rich_text_advanced_container_surface" DEFAULT 'none';
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_container_radius" "enum__pages_v_blocks_rich_text_advanced_container_radius" DEFAULT 'md';
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_container_shadow" "enum__pages_v_blocks_rich_text_advanced_container_shadow" DEFAULT 'none';
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_container_inner_padding" "enum__pages_v_blocks_rich_text_advanced_container_inner_padding" DEFAULT 'standard';
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_container_border_style" "enum__pages_v_blocks_rich_text_advanced_container_border_style" DEFAULT 'none';
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_callouts_highlight_mode" "enum__pages_v_blocks_rich_text_advanced_callouts_highlight_mode" DEFAULT 'none';
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_callouts_highlight_text" varchar;
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_colors_text_color" varchar;
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_colors_heading_color" varchar;
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_colors_link_color" varchar;
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_colors_accent_color" varchar;
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_colors_background_color" varchar;
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "advanced_colors_border_color" varchar;
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_typography_text_size" "enum_posts_blocks_rich_text_advanced_typography_text_size" DEFAULT 'md';
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_typography_line_height" "enum_posts_blocks_rich_text_advanced_typography_line_height" DEFAULT 'normal';
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_typography_text_align" "enum_posts_blocks_rich_text_advanced_typography_text_align" DEFAULT 'left';
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_typography_lead_style" "enum_posts_blocks_rich_text_advanced_typography_lead_style" DEFAULT 'none';
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_typography_drop_cap" "enum_posts_blocks_rich_text_advanced_typography_drop_cap" DEFAULT 'none';
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_layout_columns" "enum_posts_blocks_rich_text_advanced_layout_columns" DEFAULT '1';
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_layout_column_gap" "enum_posts_blocks_rich_text_advanced_layout_column_gap" DEFAULT 'md';
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_layout_max_width" "enum_posts_blocks_rich_text_advanced_layout_max_width" DEFAULT 'standard';
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_container_surface" "enum_posts_blocks_rich_text_advanced_container_surface" DEFAULT 'none';
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_container_radius" "enum_posts_blocks_rich_text_advanced_container_radius" DEFAULT 'md';
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_container_shadow" "enum_posts_blocks_rich_text_advanced_container_shadow" DEFAULT 'none';
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_container_inner_padding" "enum_posts_blocks_rich_text_advanced_container_inner_padding" DEFAULT 'standard';
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_container_border_style" "enum_posts_blocks_rich_text_advanced_container_border_style" DEFAULT 'none';
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_callouts_highlight_mode" "enum_posts_blocks_rich_text_advanced_callouts_highlight_mode" DEFAULT 'none';
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_callouts_highlight_text" varchar;
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_colors_text_color" varchar;
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_colors_heading_color" varchar;
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_colors_link_color" varchar;
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_colors_accent_color" varchar;
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_colors_background_color" varchar;
  ALTER TABLE "posts_blocks_rich_text" ADD COLUMN "advanced_colors_border_color" varchar;
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_typography_text_size" "enum__posts_v_blocks_rich_text_advanced_typography_text_size" DEFAULT 'md';
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_typography_line_height" "enum__posts_v_blocks_rich_text_advanced_typography_line_height" DEFAULT 'normal';
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_typography_text_align" "enum__posts_v_blocks_rich_text_advanced_typography_text_align" DEFAULT 'left';
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_typography_lead_style" "enum__posts_v_blocks_rich_text_advanced_typography_lead_style" DEFAULT 'none';
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_typography_drop_cap" "enum__posts_v_blocks_rich_text_advanced_typography_drop_cap" DEFAULT 'none';
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_layout_columns" "enum__posts_v_blocks_rich_text_advanced_layout_columns" DEFAULT '1';
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_layout_column_gap" "enum__posts_v_blocks_rich_text_advanced_layout_column_gap" DEFAULT 'md';
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_layout_max_width" "enum__posts_v_blocks_rich_text_advanced_layout_max_width" DEFAULT 'standard';
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_container_surface" "enum__posts_v_blocks_rich_text_advanced_container_surface" DEFAULT 'none';
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_container_radius" "enum__posts_v_blocks_rich_text_advanced_container_radius" DEFAULT 'md';
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_container_shadow" "enum__posts_v_blocks_rich_text_advanced_container_shadow" DEFAULT 'none';
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_container_inner_padding" "enum__posts_v_blocks_rich_text_advanced_container_inner_padding" DEFAULT 'standard';
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_container_border_style" "enum__posts_v_blocks_rich_text_advanced_container_border_style" DEFAULT 'none';
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_callouts_highlight_mode" "enum__posts_v_blocks_rich_text_advanced_callouts_highlight_mode" DEFAULT 'none';
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_callouts_highlight_text" varchar;
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_colors_text_color" varchar;
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_colors_heading_color" varchar;
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_colors_link_color" varchar;
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_colors_accent_color" varchar;
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_colors_background_color" varchar;
  ALTER TABLE "_posts_v_blocks_rich_text" ADD COLUMN "advanced_colors_border_color" varchar;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_typography_text_size";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_typography_line_height";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_typography_text_align";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_typography_lead_style";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_typography_drop_cap";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_layout_columns";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_layout_column_gap";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_layout_max_width";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_container_surface";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_container_radius";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_container_shadow";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_container_inner_padding";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_container_border_style";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_callouts_highlight_mode";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_callouts_highlight_text";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_colors_text_color";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_colors_heading_color";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_colors_link_color";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_colors_accent_color";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_colors_background_color";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "advanced_colors_border_color";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_typography_text_size";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_typography_line_height";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_typography_text_align";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_typography_lead_style";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_typography_drop_cap";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_layout_columns";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_layout_column_gap";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_layout_max_width";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_container_surface";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_container_radius";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_container_shadow";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_container_inner_padding";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_container_border_style";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_callouts_highlight_mode";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_callouts_highlight_text";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_colors_text_color";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_colors_heading_color";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_colors_link_color";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_colors_accent_color";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_colors_background_color";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "advanced_colors_border_color";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_typography_text_size";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_typography_line_height";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_typography_text_align";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_typography_lead_style";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_typography_drop_cap";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_layout_columns";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_layout_column_gap";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_layout_max_width";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_container_surface";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_container_radius";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_container_shadow";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_container_inner_padding";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_container_border_style";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_callouts_highlight_mode";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_callouts_highlight_text";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_colors_text_color";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_colors_heading_color";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_colors_link_color";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_colors_accent_color";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_colors_background_color";
  ALTER TABLE "posts_blocks_rich_text" DROP COLUMN "advanced_colors_border_color";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_typography_text_size";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_typography_line_height";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_typography_text_align";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_typography_lead_style";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_typography_drop_cap";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_layout_columns";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_layout_column_gap";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_layout_max_width";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_container_surface";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_container_radius";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_container_shadow";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_container_inner_padding";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_container_border_style";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_callouts_highlight_mode";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_callouts_highlight_text";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_colors_text_color";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_colors_heading_color";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_colors_link_color";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_colors_accent_color";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_colors_background_color";
  ALTER TABLE "_posts_v_blocks_rich_text" DROP COLUMN "advanced_colors_border_color";
  DROP TYPE "public"."enum_pages_blocks_rich_text_advanced_typography_text_size";
  DROP TYPE "public"."enum_pages_blocks_rich_text_advanced_typography_line_height";
  DROP TYPE "public"."enum_pages_blocks_rich_text_advanced_typography_text_align";
  DROP TYPE "public"."enum_pages_blocks_rich_text_advanced_typography_lead_style";
  DROP TYPE "public"."enum_pages_blocks_rich_text_advanced_typography_drop_cap";
  DROP TYPE "public"."enum_pages_blocks_rich_text_advanced_layout_columns";
  DROP TYPE "public"."enum_pages_blocks_rich_text_advanced_layout_column_gap";
  DROP TYPE "public"."enum_pages_blocks_rich_text_advanced_layout_max_width";
  DROP TYPE "public"."enum_pages_blocks_rich_text_advanced_container_surface";
  DROP TYPE "public"."enum_pages_blocks_rich_text_advanced_container_radius";
  DROP TYPE "public"."enum_pages_blocks_rich_text_advanced_container_shadow";
  DROP TYPE "public"."enum_pages_blocks_rich_text_advanced_container_inner_padding";
  DROP TYPE "public"."enum_pages_blocks_rich_text_advanced_container_border_style";
  DROP TYPE "public"."enum_pages_blocks_rich_text_advanced_callouts_highlight_mode";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_advanced_typography_text_size";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_advanced_typography_line_height";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_advanced_typography_text_align";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_advanced_typography_lead_style";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_advanced_typography_drop_cap";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_advanced_layout_columns";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_advanced_layout_column_gap";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_advanced_layout_max_width";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_advanced_container_surface";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_advanced_container_radius";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_advanced_container_shadow";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_advanced_container_inner_padding";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_advanced_container_border_style";
  DROP TYPE "public"."enum__pages_v_blocks_rich_text_advanced_callouts_highlight_mode";
  DROP TYPE "public"."enum_posts_blocks_rich_text_advanced_typography_text_size";
  DROP TYPE "public"."enum_posts_blocks_rich_text_advanced_typography_line_height";
  DROP TYPE "public"."enum_posts_blocks_rich_text_advanced_typography_text_align";
  DROP TYPE "public"."enum_posts_blocks_rich_text_advanced_typography_lead_style";
  DROP TYPE "public"."enum_posts_blocks_rich_text_advanced_typography_drop_cap";
  DROP TYPE "public"."enum_posts_blocks_rich_text_advanced_layout_columns";
  DROP TYPE "public"."enum_posts_blocks_rich_text_advanced_layout_column_gap";
  DROP TYPE "public"."enum_posts_blocks_rich_text_advanced_layout_max_width";
  DROP TYPE "public"."enum_posts_blocks_rich_text_advanced_container_surface";
  DROP TYPE "public"."enum_posts_blocks_rich_text_advanced_container_radius";
  DROP TYPE "public"."enum_posts_blocks_rich_text_advanced_container_shadow";
  DROP TYPE "public"."enum_posts_blocks_rich_text_advanced_container_inner_padding";
  DROP TYPE "public"."enum_posts_blocks_rich_text_advanced_container_border_style";
  DROP TYPE "public"."enum_posts_blocks_rich_text_advanced_callouts_highlight_mode";
  DROP TYPE "public"."enum__posts_v_blocks_rich_text_advanced_typography_text_size";
  DROP TYPE "public"."enum__posts_v_blocks_rich_text_advanced_typography_line_height";
  DROP TYPE "public"."enum__posts_v_blocks_rich_text_advanced_typography_text_align";
  DROP TYPE "public"."enum__posts_v_blocks_rich_text_advanced_typography_lead_style";
  DROP TYPE "public"."enum__posts_v_blocks_rich_text_advanced_typography_drop_cap";
  DROP TYPE "public"."enum__posts_v_blocks_rich_text_advanced_layout_columns";
  DROP TYPE "public"."enum__posts_v_blocks_rich_text_advanced_layout_column_gap";
  DROP TYPE "public"."enum__posts_v_blocks_rich_text_advanced_layout_max_width";
  DROP TYPE "public"."enum__posts_v_blocks_rich_text_advanced_container_surface";
  DROP TYPE "public"."enum__posts_v_blocks_rich_text_advanced_container_radius";
  DROP TYPE "public"."enum__posts_v_blocks_rich_text_advanced_container_shadow";
  DROP TYPE "public"."enum__posts_v_blocks_rich_text_advanced_container_inner_padding";
  DROP TYPE "public"."enum__posts_v_blocks_rich_text_advanced_container_border_style";
  DROP TYPE "public"."enum__posts_v_blocks_rich_text_advanced_callouts_highlight_mode";`)
}
