import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_blocks_cards_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum_pages_blocks_cards_advanced_columns" AS ENUM('2', '3', '4');
  CREATE TYPE "public"."enum_pages_blocks_cta_section_advanced_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_pages_blocks_media_block_advanced_frame_style" AS ENUM('none', 'outline', 'card');
  CREATE TYPE "public"."enum_pages_blocks_media_block_advanced_radius" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_media_block_advanced_shadow" AS ENUM('none', 'soft', 'medium');
  CREATE TYPE "public"."enum_pages_blocks_faq_advanced_layout" AS ENUM('cards', 'minimal');
  CREATE TYPE "public"."enum_pages_blocks_faq_advanced_columns" AS ENUM('1', '2');
  CREATE TYPE "public"."enum_pages_blocks_content_list_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum_pages_blocks_stats_advanced_columns" AS ENUM('2', '3', '4');
  CREATE TYPE "public"."enum_pages_blocks_stats_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum_pages_blocks_logo_cloud_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum_pages_blocks_logo_cloud_advanced_columns" AS ENUM('2', '3', '4', '6');
  CREATE TYPE "public"."enum_pages_blocks_timeline_advanced_style" AS ENUM('cards', 'minimal');
  CREATE TYPE "public"."enum_pages_blocks_newsletter_advanced_tone" AS ENUM('light', 'dark');
  CREATE TYPE "public"."enum_pages_blocks_newsletter_advanced_layout" AS ENUM('inline', 'stacked');
  CREATE TYPE "public"."enum_pages_blocks_newsletter_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum_pages_blocks_two_column_rich_text_advanced_gap" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."v_align" AS ENUM('top', 'center');
  CREATE TYPE "public"."enum_pages_blocks_pricing_advanced_columns" AS ENUM('2', '3', '4');
  CREATE TYPE "public"."enum_pages_blocks_pricing_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum_pages_blocks_pricing_advanced_highlight_style" AS ENUM('solid', 'outline');
  CREATE TYPE "public"."enum_pages_blocks_video_embed_advanced_frame_style" AS ENUM('none', 'outline', 'card');
  CREATE TYPE "public"."enum_pages_blocks_video_embed_advanced_radius" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum_pages_blocks_video_embed_advanced_shadow" AS ENUM('none', 'soft', 'medium');
  CREATE TYPE "public"."enum_pages_blocks_data_viz_advanced_panel_style" AS ENUM('none', 'soft', 'card');
  CREATE TYPE "public"."enum__pages_v_blocks_cards_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum__pages_v_blocks_cards_advanced_columns" AS ENUM('2', '3', '4');
  CREATE TYPE "public"."enum__pages_v_blocks_cta_section_advanced_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_advanced_frame_style" AS ENUM('none', 'outline', 'card');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_advanced_radius" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_media_block_advanced_shadow" AS ENUM('none', 'soft', 'medium');
  CREATE TYPE "public"."enum__pages_v_blocks_faq_advanced_layout" AS ENUM('cards', 'minimal');
  CREATE TYPE "public"."enum__pages_v_blocks_faq_advanced_columns" AS ENUM('1', '2');
  CREATE TYPE "public"."enum__pages_v_blocks_content_list_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum__pages_v_blocks_stats_advanced_columns" AS ENUM('2', '3', '4');
  CREATE TYPE "public"."enum__pages_v_blocks_stats_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum__pages_v_blocks_logo_cloud_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum__pages_v_blocks_logo_cloud_advanced_columns" AS ENUM('2', '3', '4', '6');
  CREATE TYPE "public"."enum__pages_v_blocks_timeline_advanced_style" AS ENUM('cards', 'minimal');
  CREATE TYPE "public"."enum__pages_v_blocks_newsletter_advanced_tone" AS ENUM('light', 'dark');
  CREATE TYPE "public"."enum__pages_v_blocks_newsletter_advanced_layout" AS ENUM('inline', 'stacked');
  CREATE TYPE "public"."enum__pages_v_blocks_newsletter_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum__pages_v_blocks_two_column_rich_text_advanced_gap" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_pricing_advanced_columns" AS ENUM('2', '3', '4');
  CREATE TYPE "public"."enum__pages_v_blocks_pricing_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum__pages_v_blocks_pricing_advanced_highlight_style" AS ENUM('solid', 'outline');
  CREATE TYPE "public"."enum__pages_v_blocks_video_embed_advanced_frame_style" AS ENUM('none', 'outline', 'card');
  CREATE TYPE "public"."enum__pages_v_blocks_video_embed_advanced_radius" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum__pages_v_blocks_video_embed_advanced_shadow" AS ENUM('none', 'soft', 'medium');
  CREATE TYPE "public"."enum__pages_v_blocks_data_viz_advanced_panel_style" AS ENUM('none', 'soft', 'card');
  CREATE TYPE "public"."enum_posts_blocks_cards_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum_posts_blocks_cards_advanced_columns" AS ENUM('2', '3', '4');
  CREATE TYPE "public"."enum_posts_blocks_cta_section_advanced_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum_posts_blocks_media_block_advanced_frame_style" AS ENUM('none', 'outline', 'card');
  CREATE TYPE "public"."enum_posts_blocks_media_block_advanced_radius" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum_posts_blocks_media_block_advanced_shadow" AS ENUM('none', 'soft', 'medium');
  CREATE TYPE "public"."enum_posts_blocks_faq_advanced_layout" AS ENUM('cards', 'minimal');
  CREATE TYPE "public"."enum_posts_blocks_faq_advanced_columns" AS ENUM('1', '2');
  CREATE TYPE "public"."enum_posts_blocks_content_list_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum_posts_blocks_stats_advanced_columns" AS ENUM('2', '3', '4');
  CREATE TYPE "public"."enum_posts_blocks_stats_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum_posts_blocks_logo_cloud_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum_posts_blocks_logo_cloud_advanced_columns" AS ENUM('2', '3', '4', '6');
  CREATE TYPE "public"."enum_posts_blocks_timeline_advanced_style" AS ENUM('cards', 'minimal');
  CREATE TYPE "public"."enum_posts_blocks_newsletter_advanced_tone" AS ENUM('light', 'dark');
  CREATE TYPE "public"."enum_posts_blocks_newsletter_advanced_layout" AS ENUM('inline', 'stacked');
  CREATE TYPE "public"."enum_posts_blocks_newsletter_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum_posts_blocks_two_column_rich_text_advanced_gap" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum_posts_blocks_pricing_advanced_columns" AS ENUM('2', '3', '4');
  CREATE TYPE "public"."enum_posts_blocks_pricing_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum_posts_blocks_pricing_advanced_highlight_style" AS ENUM('solid', 'outline');
  CREATE TYPE "public"."enum_posts_blocks_video_embed_advanced_frame_style" AS ENUM('none', 'outline', 'card');
  CREATE TYPE "public"."enum_posts_blocks_video_embed_advanced_radius" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum_posts_blocks_video_embed_advanced_shadow" AS ENUM('none', 'soft', 'medium');
  CREATE TYPE "public"."enum_posts_blocks_data_viz_advanced_panel_style" AS ENUM('none', 'soft', 'card');
  CREATE TYPE "public"."enum__posts_v_blocks_cards_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum__posts_v_blocks_cards_advanced_columns" AS ENUM('2', '3', '4');
  CREATE TYPE "public"."enum__posts_v_blocks_cta_section_advanced_align" AS ENUM('left', 'center');
  CREATE TYPE "public"."enum__posts_v_blocks_media_block_advanced_frame_style" AS ENUM('none', 'outline', 'card');
  CREATE TYPE "public"."enum__posts_v_blocks_media_block_advanced_radius" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum__posts_v_blocks_media_block_advanced_shadow" AS ENUM('none', 'soft', 'medium');
  CREATE TYPE "public"."enum__posts_v_blocks_faq_advanced_layout" AS ENUM('cards', 'minimal');
  CREATE TYPE "public"."enum__posts_v_blocks_faq_advanced_columns" AS ENUM('1', '2');
  CREATE TYPE "public"."enum__posts_v_blocks_content_list_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum__posts_v_blocks_stats_advanced_columns" AS ENUM('2', '3', '4');
  CREATE TYPE "public"."enum__posts_v_blocks_stats_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum__posts_v_blocks_logo_cloud_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum__posts_v_blocks_logo_cloud_advanced_columns" AS ENUM('2', '3', '4', '6');
  CREATE TYPE "public"."enum__posts_v_blocks_timeline_advanced_style" AS ENUM('cards', 'minimal');
  CREATE TYPE "public"."enum__posts_v_blocks_newsletter_advanced_tone" AS ENUM('light', 'dark');
  CREATE TYPE "public"."enum__posts_v_blocks_newsletter_advanced_layout" AS ENUM('inline', 'stacked');
  CREATE TYPE "public"."enum__posts_v_blocks_newsletter_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum__posts_v_blocks_two_column_rich_text_advanced_gap" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum__posts_v_blocks_pricing_advanced_columns" AS ENUM('2', '3', '4');
  CREATE TYPE "public"."enum__posts_v_blocks_pricing_advanced_card_style" AS ENUM('flat', 'raised');
  CREATE TYPE "public"."enum__posts_v_blocks_pricing_advanced_highlight_style" AS ENUM('solid', 'outline');
  CREATE TYPE "public"."enum__posts_v_blocks_video_embed_advanced_frame_style" AS ENUM('none', 'outline', 'card');
  CREATE TYPE "public"."enum__posts_v_blocks_video_embed_advanced_radius" AS ENUM('sm', 'md', 'lg');
  CREATE TYPE "public"."enum__posts_v_blocks_video_embed_advanced_shadow" AS ENUM('none', 'soft', 'medium');
  CREATE TYPE "public"."enum__posts_v_blocks_data_viz_advanced_panel_style" AS ENUM('none', 'soft', 'card');
  ALTER TABLE "pages_blocks_cards" ADD COLUMN "advanced_card_style" "enum_pages_blocks_cards_advanced_card_style" DEFAULT 'raised';
  ALTER TABLE "pages_blocks_cards" ADD COLUMN "advanced_columns" "enum_pages_blocks_cards_advanced_columns" DEFAULT '2';
  ALTER TABLE "pages_blocks_cta_section" ADD COLUMN "advanced_align" "enum_pages_blocks_cta_section_advanced_align" DEFAULT 'left';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "advanced_frame_style" "enum_pages_blocks_media_block_advanced_frame_style" DEFAULT 'outline';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "advanced_radius" "enum_pages_blocks_media_block_advanced_radius" DEFAULT 'md';
  ALTER TABLE "pages_blocks_media_block" ADD COLUMN "advanced_shadow" "enum_pages_blocks_media_block_advanced_shadow" DEFAULT 'none';
  ALTER TABLE "pages_blocks_faq" ADD COLUMN "advanced_layout" "enum_pages_blocks_faq_advanced_layout" DEFAULT 'cards';
  ALTER TABLE "pages_blocks_faq" ADD COLUMN "advanced_columns" "enum_pages_blocks_faq_advanced_columns" DEFAULT '1';
  ALTER TABLE "pages_blocks_content_list" ADD COLUMN "advanced_card_style" "enum_pages_blocks_content_list_advanced_card_style" DEFAULT 'raised';
  ALTER TABLE "pages_blocks_content_list" ADD COLUMN "advanced_show_images" boolean DEFAULT true;
  ALTER TABLE "pages_blocks_content_list" ADD COLUMN "advanced_dense" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "advanced_columns" "enum_pages_blocks_stats_advanced_columns" DEFAULT '3';
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "advanced_card_style" "enum_pages_blocks_stats_advanced_card_style" DEFAULT 'flat';
  ALTER TABLE "pages_blocks_logo_cloud" ADD COLUMN "advanced_card_style" "enum_pages_blocks_logo_cloud_advanced_card_style" DEFAULT 'flat';
  ALTER TABLE "pages_blocks_logo_cloud" ADD COLUMN "advanced_columns" "enum_pages_blocks_logo_cloud_advanced_columns" DEFAULT '4';
  ALTER TABLE "pages_blocks_timeline" ADD COLUMN "advanced_style" "enum_pages_blocks_timeline_advanced_style" DEFAULT 'cards';
  ALTER TABLE "pages_blocks_timeline" ADD COLUMN "advanced_compact" boolean DEFAULT false;
  ALTER TABLE "pages_blocks_newsletter" ADD COLUMN "advanced_tone" "enum_pages_blocks_newsletter_advanced_tone" DEFAULT 'light';
  ALTER TABLE "pages_blocks_newsletter" ADD COLUMN "advanced_layout" "enum_pages_blocks_newsletter_advanced_layout" DEFAULT 'inline';
  ALTER TABLE "pages_blocks_newsletter" ADD COLUMN "advanced_card_style" "enum_pages_blocks_newsletter_advanced_card_style" DEFAULT 'flat';
  ALTER TABLE "pages_blocks_two_column_rich_text" ADD COLUMN "advanced_gap" "enum_pages_blocks_two_column_rich_text_advanced_gap" DEFAULT 'md';
  ALTER TABLE "pages_blocks_two_column_rich_text" ADD COLUMN "advanced_vertical_align" "v_align" DEFAULT 'top';
  ALTER TABLE "pages_blocks_pricing" ADD COLUMN "advanced_columns" "enum_pages_blocks_pricing_advanced_columns" DEFAULT '3';
  ALTER TABLE "pages_blocks_pricing" ADD COLUMN "advanced_card_style" "enum_pages_blocks_pricing_advanced_card_style" DEFAULT 'flat';
  ALTER TABLE "pages_blocks_pricing" ADD COLUMN "advanced_highlight_style" "enum_pages_blocks_pricing_advanced_highlight_style" DEFAULT 'solid';
  ALTER TABLE "pages_blocks_video_embed" ADD COLUMN "advanced_frame_style" "enum_pages_blocks_video_embed_advanced_frame_style" DEFAULT 'outline';
  ALTER TABLE "pages_blocks_video_embed" ADD COLUMN "advanced_radius" "enum_pages_blocks_video_embed_advanced_radius" DEFAULT 'md';
  ALTER TABLE "pages_blocks_video_embed" ADD COLUMN "advanced_shadow" "enum_pages_blocks_video_embed_advanced_shadow" DEFAULT 'none';
  ALTER TABLE "pages_blocks_data_viz" ADD COLUMN "advanced_panel_style" "enum_pages_blocks_data_viz_advanced_panel_style" DEFAULT 'none';
  ALTER TABLE "_pages_v_blocks_cards" ADD COLUMN "advanced_card_style" "enum__pages_v_blocks_cards_advanced_card_style" DEFAULT 'raised';
  ALTER TABLE "_pages_v_blocks_cards" ADD COLUMN "advanced_columns" "enum__pages_v_blocks_cards_advanced_columns" DEFAULT '2';
  ALTER TABLE "_pages_v_blocks_cta_section" ADD COLUMN "advanced_align" "enum__pages_v_blocks_cta_section_advanced_align" DEFAULT 'left';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "advanced_frame_style" "enum__pages_v_blocks_media_block_advanced_frame_style" DEFAULT 'outline';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "advanced_radius" "enum__pages_v_blocks_media_block_advanced_radius" DEFAULT 'md';
  ALTER TABLE "_pages_v_blocks_media_block" ADD COLUMN "advanced_shadow" "enum__pages_v_blocks_media_block_advanced_shadow" DEFAULT 'none';
  ALTER TABLE "_pages_v_blocks_faq" ADD COLUMN "advanced_layout" "enum__pages_v_blocks_faq_advanced_layout" DEFAULT 'cards';
  ALTER TABLE "_pages_v_blocks_faq" ADD COLUMN "advanced_columns" "enum__pages_v_blocks_faq_advanced_columns" DEFAULT '1';
  ALTER TABLE "_pages_v_blocks_content_list" ADD COLUMN "advanced_card_style" "enum__pages_v_blocks_content_list_advanced_card_style" DEFAULT 'raised';
  ALTER TABLE "_pages_v_blocks_content_list" ADD COLUMN "advanced_show_images" boolean DEFAULT true;
  ALTER TABLE "_pages_v_blocks_content_list" ADD COLUMN "advanced_dense" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "advanced_columns" "enum__pages_v_blocks_stats_advanced_columns" DEFAULT '3';
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "advanced_card_style" "enum__pages_v_blocks_stats_advanced_card_style" DEFAULT 'flat';
  ALTER TABLE "_pages_v_blocks_logo_cloud" ADD COLUMN "advanced_card_style" "enum__pages_v_blocks_logo_cloud_advanced_card_style" DEFAULT 'flat';
  ALTER TABLE "_pages_v_blocks_logo_cloud" ADD COLUMN "advanced_columns" "enum__pages_v_blocks_logo_cloud_advanced_columns" DEFAULT '4';
  ALTER TABLE "_pages_v_blocks_timeline" ADD COLUMN "advanced_style" "enum__pages_v_blocks_timeline_advanced_style" DEFAULT 'cards';
  ALTER TABLE "_pages_v_blocks_timeline" ADD COLUMN "advanced_compact" boolean DEFAULT false;
  ALTER TABLE "_pages_v_blocks_newsletter" ADD COLUMN "advanced_tone" "enum__pages_v_blocks_newsletter_advanced_tone" DEFAULT 'light';
  ALTER TABLE "_pages_v_blocks_newsletter" ADD COLUMN "advanced_layout" "enum__pages_v_blocks_newsletter_advanced_layout" DEFAULT 'inline';
  ALTER TABLE "_pages_v_blocks_newsletter" ADD COLUMN "advanced_card_style" "enum__pages_v_blocks_newsletter_advanced_card_style" DEFAULT 'flat';
  ALTER TABLE "_pages_v_blocks_two_column_rich_text" ADD COLUMN "advanced_gap" "enum__pages_v_blocks_two_column_rich_text_advanced_gap" DEFAULT 'md';
  ALTER TABLE "_pages_v_blocks_two_column_rich_text" ADD COLUMN "advanced_vertical_align" "v_align" DEFAULT 'top';
  ALTER TABLE "_pages_v_blocks_pricing" ADD COLUMN "advanced_columns" "enum__pages_v_blocks_pricing_advanced_columns" DEFAULT '3';
  ALTER TABLE "_pages_v_blocks_pricing" ADD COLUMN "advanced_card_style" "enum__pages_v_blocks_pricing_advanced_card_style" DEFAULT 'flat';
  ALTER TABLE "_pages_v_blocks_pricing" ADD COLUMN "advanced_highlight_style" "enum__pages_v_blocks_pricing_advanced_highlight_style" DEFAULT 'solid';
  ALTER TABLE "_pages_v_blocks_video_embed" ADD COLUMN "advanced_frame_style" "enum__pages_v_blocks_video_embed_advanced_frame_style" DEFAULT 'outline';
  ALTER TABLE "_pages_v_blocks_video_embed" ADD COLUMN "advanced_radius" "enum__pages_v_blocks_video_embed_advanced_radius" DEFAULT 'md';
  ALTER TABLE "_pages_v_blocks_video_embed" ADD COLUMN "advanced_shadow" "enum__pages_v_blocks_video_embed_advanced_shadow" DEFAULT 'none';
  ALTER TABLE "_pages_v_blocks_data_viz" ADD COLUMN "advanced_panel_style" "enum__pages_v_blocks_data_viz_advanced_panel_style" DEFAULT 'none';
  ALTER TABLE "posts_blocks_cards" ADD COLUMN "advanced_card_style" "enum_posts_blocks_cards_advanced_card_style" DEFAULT 'raised';
  ALTER TABLE "posts_blocks_cards" ADD COLUMN "advanced_columns" "enum_posts_blocks_cards_advanced_columns" DEFAULT '2';
  ALTER TABLE "posts_blocks_cta_section" ADD COLUMN "advanced_align" "enum_posts_blocks_cta_section_advanced_align" DEFAULT 'left';
  ALTER TABLE "posts_blocks_media_block" ADD COLUMN "advanced_frame_style" "enum_posts_blocks_media_block_advanced_frame_style" DEFAULT 'outline';
  ALTER TABLE "posts_blocks_media_block" ADD COLUMN "advanced_radius" "enum_posts_blocks_media_block_advanced_radius" DEFAULT 'md';
  ALTER TABLE "posts_blocks_media_block" ADD COLUMN "advanced_shadow" "enum_posts_blocks_media_block_advanced_shadow" DEFAULT 'none';
  ALTER TABLE "posts_blocks_faq" ADD COLUMN "advanced_layout" "enum_posts_blocks_faq_advanced_layout" DEFAULT 'cards';
  ALTER TABLE "posts_blocks_faq" ADD COLUMN "advanced_columns" "enum_posts_blocks_faq_advanced_columns" DEFAULT '1';
  ALTER TABLE "posts_blocks_content_list" ADD COLUMN "advanced_card_style" "enum_posts_blocks_content_list_advanced_card_style" DEFAULT 'raised';
  ALTER TABLE "posts_blocks_content_list" ADD COLUMN "advanced_show_images" boolean DEFAULT true;
  ALTER TABLE "posts_blocks_content_list" ADD COLUMN "advanced_dense" boolean DEFAULT false;
  ALTER TABLE "posts_blocks_stats" ADD COLUMN "advanced_columns" "enum_posts_blocks_stats_advanced_columns" DEFAULT '3';
  ALTER TABLE "posts_blocks_stats" ADD COLUMN "advanced_card_style" "enum_posts_blocks_stats_advanced_card_style" DEFAULT 'flat';
  ALTER TABLE "posts_blocks_logo_cloud" ADD COLUMN "advanced_card_style" "enum_posts_blocks_logo_cloud_advanced_card_style" DEFAULT 'flat';
  ALTER TABLE "posts_blocks_logo_cloud" ADD COLUMN "advanced_columns" "enum_posts_blocks_logo_cloud_advanced_columns" DEFAULT '4';
  ALTER TABLE "posts_blocks_timeline" ADD COLUMN "advanced_style" "enum_posts_blocks_timeline_advanced_style" DEFAULT 'cards';
  ALTER TABLE "posts_blocks_timeline" ADD COLUMN "advanced_compact" boolean DEFAULT false;
  ALTER TABLE "posts_blocks_newsletter" ADD COLUMN "advanced_tone" "enum_posts_blocks_newsletter_advanced_tone" DEFAULT 'light';
  ALTER TABLE "posts_blocks_newsletter" ADD COLUMN "advanced_layout" "enum_posts_blocks_newsletter_advanced_layout" DEFAULT 'inline';
  ALTER TABLE "posts_blocks_newsletter" ADD COLUMN "advanced_card_style" "enum_posts_blocks_newsletter_advanced_card_style" DEFAULT 'flat';
  ALTER TABLE "posts_blocks_two_column_rich_text" ADD COLUMN "advanced_gap" "enum_posts_blocks_two_column_rich_text_advanced_gap" DEFAULT 'md';
  ALTER TABLE "posts_blocks_two_column_rich_text" ADD COLUMN "advanced_vertical_align" "v_align" DEFAULT 'top';
  ALTER TABLE "posts_blocks_pricing" ADD COLUMN "advanced_columns" "enum_posts_blocks_pricing_advanced_columns" DEFAULT '3';
  ALTER TABLE "posts_blocks_pricing" ADD COLUMN "advanced_card_style" "enum_posts_blocks_pricing_advanced_card_style" DEFAULT 'flat';
  ALTER TABLE "posts_blocks_pricing" ADD COLUMN "advanced_highlight_style" "enum_posts_blocks_pricing_advanced_highlight_style" DEFAULT 'solid';
  ALTER TABLE "posts_blocks_video_embed" ADD COLUMN "advanced_frame_style" "enum_posts_blocks_video_embed_advanced_frame_style" DEFAULT 'outline';
  ALTER TABLE "posts_blocks_video_embed" ADD COLUMN "advanced_radius" "enum_posts_blocks_video_embed_advanced_radius" DEFAULT 'md';
  ALTER TABLE "posts_blocks_video_embed" ADD COLUMN "advanced_shadow" "enum_posts_blocks_video_embed_advanced_shadow" DEFAULT 'none';
  ALTER TABLE "posts_blocks_data_viz" ADD COLUMN "advanced_panel_style" "enum_posts_blocks_data_viz_advanced_panel_style" DEFAULT 'none';
  ALTER TABLE "_posts_v_blocks_cards" ADD COLUMN "advanced_card_style" "enum__posts_v_blocks_cards_advanced_card_style" DEFAULT 'raised';
  ALTER TABLE "_posts_v_blocks_cards" ADD COLUMN "advanced_columns" "enum__posts_v_blocks_cards_advanced_columns" DEFAULT '2';
  ALTER TABLE "_posts_v_blocks_cta_section" ADD COLUMN "advanced_align" "enum__posts_v_blocks_cta_section_advanced_align" DEFAULT 'left';
  ALTER TABLE "_posts_v_blocks_media_block" ADD COLUMN "advanced_frame_style" "enum__posts_v_blocks_media_block_advanced_frame_style" DEFAULT 'outline';
  ALTER TABLE "_posts_v_blocks_media_block" ADD COLUMN "advanced_radius" "enum__posts_v_blocks_media_block_advanced_radius" DEFAULT 'md';
  ALTER TABLE "_posts_v_blocks_media_block" ADD COLUMN "advanced_shadow" "enum__posts_v_blocks_media_block_advanced_shadow" DEFAULT 'none';
  ALTER TABLE "_posts_v_blocks_faq" ADD COLUMN "advanced_layout" "enum__posts_v_blocks_faq_advanced_layout" DEFAULT 'cards';
  ALTER TABLE "_posts_v_blocks_faq" ADD COLUMN "advanced_columns" "enum__posts_v_blocks_faq_advanced_columns" DEFAULT '1';
  ALTER TABLE "_posts_v_blocks_content_list" ADD COLUMN "advanced_card_style" "enum__posts_v_blocks_content_list_advanced_card_style" DEFAULT 'raised';
  ALTER TABLE "_posts_v_blocks_content_list" ADD COLUMN "advanced_show_images" boolean DEFAULT true;
  ALTER TABLE "_posts_v_blocks_content_list" ADD COLUMN "advanced_dense" boolean DEFAULT false;
  ALTER TABLE "_posts_v_blocks_stats" ADD COLUMN "advanced_columns" "enum__posts_v_blocks_stats_advanced_columns" DEFAULT '3';
  ALTER TABLE "_posts_v_blocks_stats" ADD COLUMN "advanced_card_style" "enum__posts_v_blocks_stats_advanced_card_style" DEFAULT 'flat';
  ALTER TABLE "_posts_v_blocks_logo_cloud" ADD COLUMN "advanced_card_style" "enum__posts_v_blocks_logo_cloud_advanced_card_style" DEFAULT 'flat';
  ALTER TABLE "_posts_v_blocks_logo_cloud" ADD COLUMN "advanced_columns" "enum__posts_v_blocks_logo_cloud_advanced_columns" DEFAULT '4';
  ALTER TABLE "_posts_v_blocks_timeline" ADD COLUMN "advanced_style" "enum__posts_v_blocks_timeline_advanced_style" DEFAULT 'cards';
  ALTER TABLE "_posts_v_blocks_timeline" ADD COLUMN "advanced_compact" boolean DEFAULT false;
  ALTER TABLE "_posts_v_blocks_newsletter" ADD COLUMN "advanced_tone" "enum__posts_v_blocks_newsletter_advanced_tone" DEFAULT 'light';
  ALTER TABLE "_posts_v_blocks_newsletter" ADD COLUMN "advanced_layout" "enum__posts_v_blocks_newsletter_advanced_layout" DEFAULT 'inline';
  ALTER TABLE "_posts_v_blocks_newsletter" ADD COLUMN "advanced_card_style" "enum__posts_v_blocks_newsletter_advanced_card_style" DEFAULT 'flat';
  ALTER TABLE "_posts_v_blocks_two_column_rich_text" ADD COLUMN "advanced_gap" "enum__posts_v_blocks_two_column_rich_text_advanced_gap" DEFAULT 'md';
  ALTER TABLE "_posts_v_blocks_two_column_rich_text" ADD COLUMN "advanced_vertical_align" "v_align" DEFAULT 'top';
  ALTER TABLE "_posts_v_blocks_pricing" ADD COLUMN "advanced_columns" "enum__posts_v_blocks_pricing_advanced_columns" DEFAULT '3';
  ALTER TABLE "_posts_v_blocks_pricing" ADD COLUMN "advanced_card_style" "enum__posts_v_blocks_pricing_advanced_card_style" DEFAULT 'flat';
  ALTER TABLE "_posts_v_blocks_pricing" ADD COLUMN "advanced_highlight_style" "enum__posts_v_blocks_pricing_advanced_highlight_style" DEFAULT 'solid';
  ALTER TABLE "_posts_v_blocks_video_embed" ADD COLUMN "advanced_frame_style" "enum__posts_v_blocks_video_embed_advanced_frame_style" DEFAULT 'outline';
  ALTER TABLE "_posts_v_blocks_video_embed" ADD COLUMN "advanced_radius" "enum__posts_v_blocks_video_embed_advanced_radius" DEFAULT 'md';
  ALTER TABLE "_posts_v_blocks_video_embed" ADD COLUMN "advanced_shadow" "enum__posts_v_blocks_video_embed_advanced_shadow" DEFAULT 'none';
  ALTER TABLE "_posts_v_blocks_data_viz" ADD COLUMN "advanced_panel_style" "enum__posts_v_blocks_data_viz_advanced_panel_style" DEFAULT 'none';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_cards" DROP COLUMN "advanced_card_style";
  ALTER TABLE "pages_blocks_cards" DROP COLUMN "advanced_columns";
  ALTER TABLE "pages_blocks_cta_section" DROP COLUMN "advanced_align";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "advanced_frame_style";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "advanced_radius";
  ALTER TABLE "pages_blocks_media_block" DROP COLUMN "advanced_shadow";
  ALTER TABLE "pages_blocks_faq" DROP COLUMN "advanced_layout";
  ALTER TABLE "pages_blocks_faq" DROP COLUMN "advanced_columns";
  ALTER TABLE "pages_blocks_content_list" DROP COLUMN "advanced_card_style";
  ALTER TABLE "pages_blocks_content_list" DROP COLUMN "advanced_show_images";
  ALTER TABLE "pages_blocks_content_list" DROP COLUMN "advanced_dense";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "advanced_columns";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "advanced_card_style";
  ALTER TABLE "pages_blocks_logo_cloud" DROP COLUMN "advanced_card_style";
  ALTER TABLE "pages_blocks_logo_cloud" DROP COLUMN "advanced_columns";
  ALTER TABLE "pages_blocks_timeline" DROP COLUMN "advanced_style";
  ALTER TABLE "pages_blocks_timeline" DROP COLUMN "advanced_compact";
  ALTER TABLE "pages_blocks_newsletter" DROP COLUMN "advanced_tone";
  ALTER TABLE "pages_blocks_newsletter" DROP COLUMN "advanced_layout";
  ALTER TABLE "pages_blocks_newsletter" DROP COLUMN "advanced_card_style";
  ALTER TABLE "pages_blocks_two_column_rich_text" DROP COLUMN "advanced_gap";
  ALTER TABLE "pages_blocks_two_column_rich_text" DROP COLUMN "advanced_vertical_align";
  ALTER TABLE "pages_blocks_pricing" DROP COLUMN "advanced_columns";
  ALTER TABLE "pages_blocks_pricing" DROP COLUMN "advanced_card_style";
  ALTER TABLE "pages_blocks_pricing" DROP COLUMN "advanced_highlight_style";
  ALTER TABLE "pages_blocks_video_embed" DROP COLUMN "advanced_frame_style";
  ALTER TABLE "pages_blocks_video_embed" DROP COLUMN "advanced_radius";
  ALTER TABLE "pages_blocks_video_embed" DROP COLUMN "advanced_shadow";
  ALTER TABLE "pages_blocks_data_viz" DROP COLUMN "advanced_panel_style";
  ALTER TABLE "_pages_v_blocks_cards" DROP COLUMN "advanced_card_style";
  ALTER TABLE "_pages_v_blocks_cards" DROP COLUMN "advanced_columns";
  ALTER TABLE "_pages_v_blocks_cta_section" DROP COLUMN "advanced_align";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "advanced_frame_style";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "advanced_radius";
  ALTER TABLE "_pages_v_blocks_media_block" DROP COLUMN "advanced_shadow";
  ALTER TABLE "_pages_v_blocks_faq" DROP COLUMN "advanced_layout";
  ALTER TABLE "_pages_v_blocks_faq" DROP COLUMN "advanced_columns";
  ALTER TABLE "_pages_v_blocks_content_list" DROP COLUMN "advanced_card_style";
  ALTER TABLE "_pages_v_blocks_content_list" DROP COLUMN "advanced_show_images";
  ALTER TABLE "_pages_v_blocks_content_list" DROP COLUMN "advanced_dense";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "advanced_columns";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "advanced_card_style";
  ALTER TABLE "_pages_v_blocks_logo_cloud" DROP COLUMN "advanced_card_style";
  ALTER TABLE "_pages_v_blocks_logo_cloud" DROP COLUMN "advanced_columns";
  ALTER TABLE "_pages_v_blocks_timeline" DROP COLUMN "advanced_style";
  ALTER TABLE "_pages_v_blocks_timeline" DROP COLUMN "advanced_compact";
  ALTER TABLE "_pages_v_blocks_newsletter" DROP COLUMN "advanced_tone";
  ALTER TABLE "_pages_v_blocks_newsletter" DROP COLUMN "advanced_layout";
  ALTER TABLE "_pages_v_blocks_newsletter" DROP COLUMN "advanced_card_style";
  ALTER TABLE "_pages_v_blocks_two_column_rich_text" DROP COLUMN "advanced_gap";
  ALTER TABLE "_pages_v_blocks_two_column_rich_text" DROP COLUMN "advanced_vertical_align";
  ALTER TABLE "_pages_v_blocks_pricing" DROP COLUMN "advanced_columns";
  ALTER TABLE "_pages_v_blocks_pricing" DROP COLUMN "advanced_card_style";
  ALTER TABLE "_pages_v_blocks_pricing" DROP COLUMN "advanced_highlight_style";
  ALTER TABLE "_pages_v_blocks_video_embed" DROP COLUMN "advanced_frame_style";
  ALTER TABLE "_pages_v_blocks_video_embed" DROP COLUMN "advanced_radius";
  ALTER TABLE "_pages_v_blocks_video_embed" DROP COLUMN "advanced_shadow";
  ALTER TABLE "_pages_v_blocks_data_viz" DROP COLUMN "advanced_panel_style";
  ALTER TABLE "posts_blocks_cards" DROP COLUMN "advanced_card_style";
  ALTER TABLE "posts_blocks_cards" DROP COLUMN "advanced_columns";
  ALTER TABLE "posts_blocks_cta_section" DROP COLUMN "advanced_align";
  ALTER TABLE "posts_blocks_media_block" DROP COLUMN "advanced_frame_style";
  ALTER TABLE "posts_blocks_media_block" DROP COLUMN "advanced_radius";
  ALTER TABLE "posts_blocks_media_block" DROP COLUMN "advanced_shadow";
  ALTER TABLE "posts_blocks_faq" DROP COLUMN "advanced_layout";
  ALTER TABLE "posts_blocks_faq" DROP COLUMN "advanced_columns";
  ALTER TABLE "posts_blocks_content_list" DROP COLUMN "advanced_card_style";
  ALTER TABLE "posts_blocks_content_list" DROP COLUMN "advanced_show_images";
  ALTER TABLE "posts_blocks_content_list" DROP COLUMN "advanced_dense";
  ALTER TABLE "posts_blocks_stats" DROP COLUMN "advanced_columns";
  ALTER TABLE "posts_blocks_stats" DROP COLUMN "advanced_card_style";
  ALTER TABLE "posts_blocks_logo_cloud" DROP COLUMN "advanced_card_style";
  ALTER TABLE "posts_blocks_logo_cloud" DROP COLUMN "advanced_columns";
  ALTER TABLE "posts_blocks_timeline" DROP COLUMN "advanced_style";
  ALTER TABLE "posts_blocks_timeline" DROP COLUMN "advanced_compact";
  ALTER TABLE "posts_blocks_newsletter" DROP COLUMN "advanced_tone";
  ALTER TABLE "posts_blocks_newsletter" DROP COLUMN "advanced_layout";
  ALTER TABLE "posts_blocks_newsletter" DROP COLUMN "advanced_card_style";
  ALTER TABLE "posts_blocks_two_column_rich_text" DROP COLUMN "advanced_gap";
  ALTER TABLE "posts_blocks_two_column_rich_text" DROP COLUMN "advanced_vertical_align";
  ALTER TABLE "posts_blocks_pricing" DROP COLUMN "advanced_columns";
  ALTER TABLE "posts_blocks_pricing" DROP COLUMN "advanced_card_style";
  ALTER TABLE "posts_blocks_pricing" DROP COLUMN "advanced_highlight_style";
  ALTER TABLE "posts_blocks_video_embed" DROP COLUMN "advanced_frame_style";
  ALTER TABLE "posts_blocks_video_embed" DROP COLUMN "advanced_radius";
  ALTER TABLE "posts_blocks_video_embed" DROP COLUMN "advanced_shadow";
  ALTER TABLE "posts_blocks_data_viz" DROP COLUMN "advanced_panel_style";
  ALTER TABLE "_posts_v_blocks_cards" DROP COLUMN "advanced_card_style";
  ALTER TABLE "_posts_v_blocks_cards" DROP COLUMN "advanced_columns";
  ALTER TABLE "_posts_v_blocks_cta_section" DROP COLUMN "advanced_align";
  ALTER TABLE "_posts_v_blocks_media_block" DROP COLUMN "advanced_frame_style";
  ALTER TABLE "_posts_v_blocks_media_block" DROP COLUMN "advanced_radius";
  ALTER TABLE "_posts_v_blocks_media_block" DROP COLUMN "advanced_shadow";
  ALTER TABLE "_posts_v_blocks_faq" DROP COLUMN "advanced_layout";
  ALTER TABLE "_posts_v_blocks_faq" DROP COLUMN "advanced_columns";
  ALTER TABLE "_posts_v_blocks_content_list" DROP COLUMN "advanced_card_style";
  ALTER TABLE "_posts_v_blocks_content_list" DROP COLUMN "advanced_show_images";
  ALTER TABLE "_posts_v_blocks_content_list" DROP COLUMN "advanced_dense";
  ALTER TABLE "_posts_v_blocks_stats" DROP COLUMN "advanced_columns";
  ALTER TABLE "_posts_v_blocks_stats" DROP COLUMN "advanced_card_style";
  ALTER TABLE "_posts_v_blocks_logo_cloud" DROP COLUMN "advanced_card_style";
  ALTER TABLE "_posts_v_blocks_logo_cloud" DROP COLUMN "advanced_columns";
  ALTER TABLE "_posts_v_blocks_timeline" DROP COLUMN "advanced_style";
  ALTER TABLE "_posts_v_blocks_timeline" DROP COLUMN "advanced_compact";
  ALTER TABLE "_posts_v_blocks_newsletter" DROP COLUMN "advanced_tone";
  ALTER TABLE "_posts_v_blocks_newsletter" DROP COLUMN "advanced_layout";
  ALTER TABLE "_posts_v_blocks_newsletter" DROP COLUMN "advanced_card_style";
  ALTER TABLE "_posts_v_blocks_two_column_rich_text" DROP COLUMN "advanced_gap";
  ALTER TABLE "_posts_v_blocks_two_column_rich_text" DROP COLUMN "advanced_vertical_align";
  ALTER TABLE "_posts_v_blocks_pricing" DROP COLUMN "advanced_columns";
  ALTER TABLE "_posts_v_blocks_pricing" DROP COLUMN "advanced_card_style";
  ALTER TABLE "_posts_v_blocks_pricing" DROP COLUMN "advanced_highlight_style";
  ALTER TABLE "_posts_v_blocks_video_embed" DROP COLUMN "advanced_frame_style";
  ALTER TABLE "_posts_v_blocks_video_embed" DROP COLUMN "advanced_radius";
  ALTER TABLE "_posts_v_blocks_video_embed" DROP COLUMN "advanced_shadow";
  ALTER TABLE "_posts_v_blocks_data_viz" DROP COLUMN "advanced_panel_style";
  DROP TYPE "public"."enum_pages_blocks_cards_advanced_card_style";
  DROP TYPE "public"."enum_pages_blocks_cards_advanced_columns";
  DROP TYPE "public"."enum_pages_blocks_cta_section_advanced_align";
  DROP TYPE "public"."enum_pages_blocks_media_block_advanced_frame_style";
  DROP TYPE "public"."enum_pages_blocks_media_block_advanced_radius";
  DROP TYPE "public"."enum_pages_blocks_media_block_advanced_shadow";
  DROP TYPE "public"."enum_pages_blocks_faq_advanced_layout";
  DROP TYPE "public"."enum_pages_blocks_faq_advanced_columns";
  DROP TYPE "public"."enum_pages_blocks_content_list_advanced_card_style";
  DROP TYPE "public"."enum_pages_blocks_stats_advanced_columns";
  DROP TYPE "public"."enum_pages_blocks_stats_advanced_card_style";
  DROP TYPE "public"."enum_pages_blocks_logo_cloud_advanced_card_style";
  DROP TYPE "public"."enum_pages_blocks_logo_cloud_advanced_columns";
  DROP TYPE "public"."enum_pages_blocks_timeline_advanced_style";
  DROP TYPE "public"."enum_pages_blocks_newsletter_advanced_tone";
  DROP TYPE "public"."enum_pages_blocks_newsletter_advanced_layout";
  DROP TYPE "public"."enum_pages_blocks_newsletter_advanced_card_style";
  DROP TYPE "public"."enum_pages_blocks_two_column_rich_text_advanced_gap";
  DROP TYPE "public"."v_align";
  DROP TYPE "public"."enum_pages_blocks_pricing_advanced_columns";
  DROP TYPE "public"."enum_pages_blocks_pricing_advanced_card_style";
  DROP TYPE "public"."enum_pages_blocks_pricing_advanced_highlight_style";
  DROP TYPE "public"."enum_pages_blocks_video_embed_advanced_frame_style";
  DROP TYPE "public"."enum_pages_blocks_video_embed_advanced_radius";
  DROP TYPE "public"."enum_pages_blocks_video_embed_advanced_shadow";
  DROP TYPE "public"."enum_pages_blocks_data_viz_advanced_panel_style";
  DROP TYPE "public"."enum__pages_v_blocks_cards_advanced_card_style";
  DROP TYPE "public"."enum__pages_v_blocks_cards_advanced_columns";
  DROP TYPE "public"."enum__pages_v_blocks_cta_section_advanced_align";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_advanced_frame_style";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_advanced_radius";
  DROP TYPE "public"."enum__pages_v_blocks_media_block_advanced_shadow";
  DROP TYPE "public"."enum__pages_v_blocks_faq_advanced_layout";
  DROP TYPE "public"."enum__pages_v_blocks_faq_advanced_columns";
  DROP TYPE "public"."enum__pages_v_blocks_content_list_advanced_card_style";
  DROP TYPE "public"."enum__pages_v_blocks_stats_advanced_columns";
  DROP TYPE "public"."enum__pages_v_blocks_stats_advanced_card_style";
  DROP TYPE "public"."enum__pages_v_blocks_logo_cloud_advanced_card_style";
  DROP TYPE "public"."enum__pages_v_blocks_logo_cloud_advanced_columns";
  DROP TYPE "public"."enum__pages_v_blocks_timeline_advanced_style";
  DROP TYPE "public"."enum__pages_v_blocks_newsletter_advanced_tone";
  DROP TYPE "public"."enum__pages_v_blocks_newsletter_advanced_layout";
  DROP TYPE "public"."enum__pages_v_blocks_newsletter_advanced_card_style";
  DROP TYPE "public"."enum__pages_v_blocks_two_column_rich_text_advanced_gap";
  DROP TYPE "public"."enum__pages_v_blocks_pricing_advanced_columns";
  DROP TYPE "public"."enum__pages_v_blocks_pricing_advanced_card_style";
  DROP TYPE "public"."enum__pages_v_blocks_pricing_advanced_highlight_style";
  DROP TYPE "public"."enum__pages_v_blocks_video_embed_advanced_frame_style";
  DROP TYPE "public"."enum__pages_v_blocks_video_embed_advanced_radius";
  DROP TYPE "public"."enum__pages_v_blocks_video_embed_advanced_shadow";
  DROP TYPE "public"."enum__pages_v_blocks_data_viz_advanced_panel_style";
  DROP TYPE "public"."enum_posts_blocks_cards_advanced_card_style";
  DROP TYPE "public"."enum_posts_blocks_cards_advanced_columns";
  DROP TYPE "public"."enum_posts_blocks_cta_section_advanced_align";
  DROP TYPE "public"."enum_posts_blocks_media_block_advanced_frame_style";
  DROP TYPE "public"."enum_posts_blocks_media_block_advanced_radius";
  DROP TYPE "public"."enum_posts_blocks_media_block_advanced_shadow";
  DROP TYPE "public"."enum_posts_blocks_faq_advanced_layout";
  DROP TYPE "public"."enum_posts_blocks_faq_advanced_columns";
  DROP TYPE "public"."enum_posts_blocks_content_list_advanced_card_style";
  DROP TYPE "public"."enum_posts_blocks_stats_advanced_columns";
  DROP TYPE "public"."enum_posts_blocks_stats_advanced_card_style";
  DROP TYPE "public"."enum_posts_blocks_logo_cloud_advanced_card_style";
  DROP TYPE "public"."enum_posts_blocks_logo_cloud_advanced_columns";
  DROP TYPE "public"."enum_posts_blocks_timeline_advanced_style";
  DROP TYPE "public"."enum_posts_blocks_newsletter_advanced_tone";
  DROP TYPE "public"."enum_posts_blocks_newsletter_advanced_layout";
  DROP TYPE "public"."enum_posts_blocks_newsletter_advanced_card_style";
  DROP TYPE "public"."enum_posts_blocks_two_column_rich_text_advanced_gap";
  DROP TYPE "public"."enum_posts_blocks_pricing_advanced_columns";
  DROP TYPE "public"."enum_posts_blocks_pricing_advanced_card_style";
  DROP TYPE "public"."enum_posts_blocks_pricing_advanced_highlight_style";
  DROP TYPE "public"."enum_posts_blocks_video_embed_advanced_frame_style";
  DROP TYPE "public"."enum_posts_blocks_video_embed_advanced_radius";
  DROP TYPE "public"."enum_posts_blocks_video_embed_advanced_shadow";
  DROP TYPE "public"."enum_posts_blocks_data_viz_advanced_panel_style";
  DROP TYPE "public"."enum__posts_v_blocks_cards_advanced_card_style";
  DROP TYPE "public"."enum__posts_v_blocks_cards_advanced_columns";
  DROP TYPE "public"."enum__posts_v_blocks_cta_section_advanced_align";
  DROP TYPE "public"."enum__posts_v_blocks_media_block_advanced_frame_style";
  DROP TYPE "public"."enum__posts_v_blocks_media_block_advanced_radius";
  DROP TYPE "public"."enum__posts_v_blocks_media_block_advanced_shadow";
  DROP TYPE "public"."enum__posts_v_blocks_faq_advanced_layout";
  DROP TYPE "public"."enum__posts_v_blocks_faq_advanced_columns";
  DROP TYPE "public"."enum__posts_v_blocks_content_list_advanced_card_style";
  DROP TYPE "public"."enum__posts_v_blocks_stats_advanced_columns";
  DROP TYPE "public"."enum__posts_v_blocks_stats_advanced_card_style";
  DROP TYPE "public"."enum__posts_v_blocks_logo_cloud_advanced_card_style";
  DROP TYPE "public"."enum__posts_v_blocks_logo_cloud_advanced_columns";
  DROP TYPE "public"."enum__posts_v_blocks_timeline_advanced_style";
  DROP TYPE "public"."enum__posts_v_blocks_newsletter_advanced_tone";
  DROP TYPE "public"."enum__posts_v_blocks_newsletter_advanced_layout";
  DROP TYPE "public"."enum__posts_v_blocks_newsletter_advanced_card_style";
  DROP TYPE "public"."enum__posts_v_blocks_two_column_rich_text_advanced_gap";
  DROP TYPE "public"."enum__posts_v_blocks_pricing_advanced_columns";
  DROP TYPE "public"."enum__posts_v_blocks_pricing_advanced_card_style";
  DROP TYPE "public"."enum__posts_v_blocks_pricing_advanced_highlight_style";
  DROP TYPE "public"."enum__posts_v_blocks_video_embed_advanced_frame_style";
  DROP TYPE "public"."enum__posts_v_blocks_video_embed_advanced_radius";
  DROP TYPE "public"."enum__posts_v_blocks_video_embed_advanced_shadow";
  DROP TYPE "public"."enum__posts_v_blocks_data_viz_advanced_panel_style";`)
}
